aurelia-v1.0.0-rc1.0.0/src/app.html, aurelia-v1.0.0-rc1.0.0/src/app.js, aurelia-v1.0.0-rc1.0.0/src/store.js
* optimized html template
* moved store to separate module and ensured code matched the inferno version
=> Aurelia tuning

bobril-v4.42.0/index.html, bobril-v4.42.0/package.json, bobril-v4.42.0/src/app.ts, bobril-v4.42.0/src/store.ts, bobril-v4.42.0/tsconfig.json, webdriver-java/src/main/java/net/stefankrause/App.java
I was not able to run selenium benchmark because it looks like expects just Mac. Hoping it will work ok.
index.html is actually regenerated by build, but I commit it anyway.
=> Bobril implementation

vue-v2.0.0-beta1/index.html, vue-v2.0.0-beta1/package.json, vue-v2.0.0-beta1/src/main.es6.js, vue-v2.0.0-beta1/src/store.es6.js, vue-v2.0.0-beta1/webpack.config.js
Copy code from vue-v1.0.26, using the vue.js 2 latest version .
In my test case, very much faster than vue.js 1.
=> add vue.js v2.0.0-beta.1 test

react-v15.2.0-mobX-v2.3.3/package.json, react-v15.2.0-mobX-v2.3.3/src/Main.jsx, react-v15.2.0-mobX-v2.3.3/src/Row.jsx, react-v15.2.0-mobX-v2.3.3/src/Store.es6.js
Most benchmarks are faster now. Somehow it didn't print the timing results after this modification for `updateData` and `select`. But it seems faster. If that is an issue when running the real benchmark I'll look into that further.
=> rewrote to more idiomatic MobX

domvm-v1.2.9/src/view.es6.js
@krausest 
the original domvm implementation was simple. this one goes a bit further and componentizes the rows, giving each an sCU condition. it's not pure perf gains across the board but cumulatively should do a bit better i think.
=> domvm impl w/subviews & sCU

index.html, ractive-edge/.babelrc, ractive-edge/index.html, ractive-edge/package.json, ractive-edge/src/main.es6.js, ractive-edge/webpack.config.js
Ractive edge is a good bit faster than 0.7.3 in most cases. If you don't mind, I'd like to see edge in the comparison table.
The template and supporting methods aren't exactly ideal examples of Ractive, but I don't suppose it's really possible to collect times _and_ have ideal examples.
=> Add Ractive edge

cleanup.sh, elm-v0.17.1/.gitignore, elm-v0.17.1/elm-package.json, elm-v0.17.1/index.html, elm-v0.17.1/package.json, elm-v0.17.1/src/Main.elm, webdriver-ts/src/common.ts
This PR aims to close #55
Randomized generation relies on [Random.Pcg](http://package.elm-lang.org/packages/mgold/elm-random-pcg/latest)
Any feedback is very welcome!
=> Added Elm benchmark

angular-v1.5.8/src/HomeController.es6.js, index.html, knockout-v3.4.0/.babelrc, knockout-v3.4.0/index.html, knockout-v3.4.0/package.json, knockout-v3.4.0/src/Main.js, knockout-v3.4.0/webpack.config.js, webdriver-ts/src/common.ts
- Added Knockout to frameworks for testing
- Fixing small issue on angular 1.5.8
=> Adding Knockout v3.4

README.md, install.js, package.json
There is a lot of packages that need to be installed for this project.
Using yarn speeds this up quite a bit.
=> Use yarn if it's installed

index.html, simulacra-v1.5.5/index.html, simulacra-v1.5.5/package.json, simulacra-v1.5.5/src/main.js
Adding my own library. Thanks for this benchmark, it helped me discover some things that I could have optimized.
There was a case that I couldn't optimize that was actually due to how Chrome recalculates styles, and I didn't change that: appending 1000 rows after 10,000 rows. It seems to be specific to Chrome and Firefox doesn't have this issue, and the performance characteristics in browsers other than Chrome seem to be quite different across all frameworks and libraries. There were even cases where Simulacra was faster than vanilla in Firefox.
=> Add Simulacra.js v1.5.5

domvm-v2.0.0-beta/package.json, domvm-v2.0.0-beta/src/main.es6.js
feel free to add this into another "keyed" folder if you plan on keeping the non-keyed versions around
=> switch domvm impl to keyed

domvm-v2.0.0-beta/package.json, domvm-v2.0.0-beta/src/main.es6.js
@krausest 
Helps alleviate moderate-to-severe "replace all rows" redness. Side-effects may include mild improvement in related areas. Use as directed.
Ain't nothin' like binary search ;)
=> update domvm, toggle homogeneous keyed list flag

README.md
Update java version because of lambda expressions used in webdriver-java
=> Update java version to >= 8

binding.scala-v10.0.1/js/src/main/scala/com/thoughtworks/binding/benchmark/Main.scala, binding.scala-v10.0.1/js/src/main/scala/com/thoughtworks/binding/benchmark/Store.scala
This is a continuation of #124
=> Recreate rows during swapping operation

domvm-v2.0.3-non-keyed/src/main.es6.js
fix non-keyed bustage caused by  #139
=> fix domvm non-keyed impl bustage

surplus-v0.4.0/index.html, surplus-v0.4.0/package.json, surplus-v0.4.0/src/controller.ts, surplus-v0.4.0/src/main.ts, surplus-v0.4.0/src/store.ts, surplus-v0.4.0/src/view.tsx, surplus-v0.4.0/tsconfig.json, surplus-v0.4.0/webpack.config.js, webdriver-ts/src/common.ts
Let me know if there are any issues.  Thanks!
=> add surplus-v0.4.0

README.md
Correction of 3 errors in the README.md
=> Spellchecking in README

.travis.yml
Have another branch adding per-job status badge. Will open PR soon.
=> Also run travis on OS X

angular-v4.1.2-no-zone-keyed/.gitignore, angular-v4.1.2-no-zone-keyed/closure.conf, angular-v4.1.2-no-zone-keyed/index.html, angular-v4.1.2-no-zone-keyed/package.json, angular-v4.1.2-no-zone-keyed/rollup.config.aot.js, angular-v4.1.2-no-zone-keyed/src/app.ts, angular-v4.1.2-no-zone-keyed/src/main.aot.ts, angular-v4.1.2-no-zone-keyed/tsconfig.json, webdriver-ts/src/common.ts
Optimized Angular implementation that does not use Zone.js, manually triggers all change detection like React does. Since it may not be a recommended way, made it a separate item.
Result going from 1.34 down to 1.26 in my local machine.
Should align with the official no-zone usage in https://github.com/angular/angular/pull/17672 after it lands.
=> introduce optimized angular without zone.js

petit-dom-v0.0.5-keyed/index.html, petit-dom-v0.0.5-keyed/package.json, petit-dom-v0.0.5-keyed/rollup.config.js, petit-dom-v0.0.5-keyed/src/index.js, petit-dom-v0.0.5-keyed/src/store.js, webdriver-ts/src/common.ts
https://github.com/yelouafi/petit-dom
=> Add petit-dom

angular-v4.3.3-keyed/closure.conf, angular-v4.3.3-no-zone-keyed/closure.conf, angular-v4.3.3-non-keyed/closure.conf
wrap all code in an IIFE to avoid naming conflict of global variables.
=> fix memory result for angular

etch-v0.12.5-keyed/.babelrc, etch-v0.12.5-keyed/index.html, etch-v0.12.5-keyed/package.json, etch-v0.12.5-keyed/src/Main.jsx, etch-v0.12.5-keyed/src/Row.jsx, etch-v0.12.5-keyed/src/Store.es6.js, etch-v0.12.5-keyed/src/main.es6.js, etch-v0.12.5-keyed/webpack.config.js, etch-v0.12.5-non-keyed/.babelrc, etch-v0.12.5-non-keyed/index.html, etch-v0.12.5-non-keyed/package.json, etch-v0.12.5-non-keyed/src/Main.jsx, etch-v0.12.5-non-keyed/src/Row.jsx, etch-v0.12.5-non-keyed/src/Store.es6.js, etch-v0.12.5-non-keyed/src/main.es6.js, etch-v0.12.5-non-keyed/webpack.config.js, webdriver-ts/src/common.ts
Add the https://github.com/atom/etch library.
=> add etch-v0.12.5

gruu-v1.6.12-keyed/.babelrc, gruu-v1.6.12-keyed/index.html, gruu-v1.6.12-keyed/package.json, gruu-v1.6.12-keyed/src/Store.es6.js, gruu-v1.6.12-keyed/src/main.es6.js, gruu-v1.6.12-keyed/webpack.config.js
I would be pleased and thankful for having Gruu introduced into the benchmarks.
Below there are the benchmark (50 runs) results compared to vanillajs-keyed.
=> Gruu v1.6.12 keyed

knockout-v3.4.1-keyed/src/Main.js
=> Use push.apply instead of arrayPushAll

choo-v6.5.0-non-keyed/index.html, choo-v6.5.0-non-keyed/package.json, choo-v6.5.0-non-keyed/src/index.js, choo-v6.5.0-non-keyed/src/rowsView.js, choo-v6.5.0-non-keyed/src/store.js, choo-v6.5.0-non-keyed/src/utils.js, webdriver-ts/src/common.ts
Following #130 #171 
Choo looks good :+1: 
I don't know it but I'm curious to see how it perform
\cc @yoshuawuyts @rahulcs
=> Add choo@6.5.0

polymer-v2.0.0-non-keyed/index.html, polymer-v2.0.0-non-keyed/package.json, polymer-v2.0.0-non-keyed/polymer.json, polymer-v2.0.0-non-keyed/src/main-element.html, webdriver-ts/src/common.ts
Use Polymer 2 native class syntax
Reference built version
=> Update Polymer 2

lit-html-v0.7.1-non-keyed/index.html, lit-html-v0.7.1-non-keyed/package.json, lit-html-v0.7.1-non-keyed/rollup.config.js, lit-html-v0.7.1-non-keyed/src/app.js, lit-html-v0.7.1-non-keyed/src/index.js, lit-html-v0.7.1-non-keyed/src/polyfill.js, webdriver-ts/src/common.ts
See: https://github.com/PolymerLabs/lit-html
=> Lit-HTML implementation

hyperhtml-v1.12.5-non-keyed/index.html, hyperhtml-v1.12.5-non-keyed/package.json, hyperhtml-v1.12.5-non-keyed/rollup.config.js, hyperhtml-v1.12.5-non-keyed/src/index.js, hyperhtml-v1.12.5-non-keyed/src/store.js, hyperhtml-v1.12.5-non-keyed/src/utils.js, webdriver-ts/src/common.ts
hyperHTML looks good :+1: 
I don't know it but I'm curious to see how it will perform 
\cc @WebReflection
=> Add hyperhtml@1.12.5

README.md
Ain't much I can do, but I love this project and wanted to participate for the longest time :P
Hope you don't mind
=> Updated the README to add round 7

webdriver-ts/src/benchmarkRunner.ts, webdriver-ts/src/benchmarks.ts
(sorry for the whitespace trimming)
=> remove redundant & inconsistent startup metrics (#330)

maik-h-v2.5.2-keyed/index.html, maik-h-v2.5.2-keyed/package.json, maik-h-v2.5.2-keyed/rollup.config.js, maik-h-v2.5.2-keyed/src/index.js, maik-h-v2.5.2-non-keyed/index.html, maik-h-v2.5.2-non-keyed/package.json, maik-h-v2.5.2-non-keyed/rollup.config.js, maik-h-v2.5.2-non-keyed/src/index.js, webdriver-ts/src/common.ts
Add library [maik.h](https://github.com/kaste/maik.h)
`maik.h` is a sibling or direct competitor of `lit-html` and `hyperhtml`, and showed surprisingly good results on my computer. Also, it's one of the few libs which supports `Rx` out of the box. 
So I thought a PR would be considered.
=> Add maik.h

attodom-v0.4.0-keyed/index.html, attodom-v0.4.0-keyed/index.js, attodom-v0.4.0-keyed/package.json, attodom-v0.4.0-keyed/src/store.js, attodom-v0.4.0-keyed/src/table.js, attodom-v0.4.0-keyed/src/time.js, webdriver-ts/src/common.ts
Hi Again,
I did not like using pico-dom, finding the abstraction confusing (not good since I wrote it).
`attodom` is faster and smaller still with a minimal api and memory footprint for mobile devices.
I suggest also removing pico-dom while merging attodom since the list resolution algorithms are essentially the same.
=> attodom-v0.4.0-keyed

angular-v5.2.2-keyed/package.json, angular-v5.2.2-no-zone-keyed/package.json, angular-v5.2.2-no-zone-keyed/src/app.ts, angular-v5.2.2-non-keyed/package.json, angular-v5.2.2-optimized-keyed/.gitignore, angular-v5.2.2-optimized-keyed/closure.conf, angular-v5.2.2-optimized-keyed/index.html, angular-v5.2.2-optimized-keyed/package.json, angular-v5.2.2-optimized-keyed/rollup.config.js, angular-v5.2.2-optimized-keyed/src/app.ts, angular-v5.2.2-optimized-keyed/src/main.ts, angular-v5.2.2-optimized-keyed/tsconfig.json
Using a custom differ in Angular (which inspired by inferno).
Other:
+ Fixed static dep version;
+ Removed the extra change detection;
=> Add an optimized Angular benchmark

aurelia-v1.1.5-non-keyed/src/store.js
using splice 2 times were producing  2 layout updates.. which hindered performance..
=> fix: aurelia swap rows perf

package.json
This reverts commit e8df2a52b3cb4a5213d97c9065da8043de04cb2f.
=> Revert "trying to fix circleci"

react-v16.1.0-redux-combiner-v0.4.1-keyed/.babelrc, react-v16.1.0-redux-combiner-v0.4.1-keyed/index.html, react-v16.1.0-redux-combiner-v0.4.1-keyed/package.json, react-v16.1.0-redux-combiner-v0.4.1-keyed/src/controller.jsx, react-v16.1.0-redux-combiner-v0.4.1-keyed/src/main.es6.js, react-v16.1.0-redux-combiner-v0.4.1-keyed/src/store.es6.js, react-v16.1.0-redux-combiner-v0.4.1-keyed/src/utils.es6.js, react-v16.1.0-redux-combiner-v0.4.1-keyed/webpack.config.js, webdriver-ts/src/common.ts
[redux-combiner](https://github.com/rmdm/redux-combiner) proposes convenient way to describe possible application state changes. It should also be quite performant.
=> add redux-combiner

frameworks/marionette-v4.0.0-jquery-keyed/package.json, frameworks/marionette-v4.0.0-jquery-keyed/src/Main.js, frameworks/marionette-v4.0.0-keyed/package.json, frameworks/marionette-v4.0.0-keyed/src/Main.js, frameworks/marionette-v4.0.0-keyed/src/mn-domapi.js
Using the beta with a couple of additional perf updates.  I don't expect to need to update this again after the beta is complete.
=> Update Marionette v4

frameworks/keyed/marionette-jquery/src/Main.js, frameworks/keyed/marionette/src/Main.js
I was told I wasn't embracing the jquery enough for this test, and they were right.
=> MnV4 change label directly perf improvement

frameworks/keyed/domc/index.html, frameworks/keyed/domc/package.json, frameworks/keyed/domc/rollup.config.js, frameworks/keyed/domc/src/app.js, frameworks/non-keyed/domc/index.html, frameworks/non-keyed/domc/package.json, frameworks/non-keyed/domc/src/app.js
- Added keyed implementation for domc
- All rendering logic is inside the library, app.js has only application logic
- Main entry point is div#main, so no feeling of 'dirty hack' should be now
=> Updated domc to 0.0.5

frameworks/non-keyed/lite-html/index.html, frameworks/non-keyed/lite-html/package.json, frameworks/non-keyed/lite-html/rollup.config.js, frameworks/non-keyed/lite-html/src/index.js
Added an implementation of the `lite-html` framework: https://github.com/ruphin/lite-html
=> Add lite-html

results-ui/package.json, results-ui/src/build.js
https://packagephobia.now.sh/result?p=yargs
https://packagephobia.now.sh/result?p=yargs-parser
```
yargs:          1.22 MB, 290 Files, 65 Folders
yargs-parser:   53.4 KB,  10 Files,  3 Folders
```
also updates rollup & uglify-js
=> [results-ui] replace yargs with yargs-parser

frameworks/keyed/stage0/app.js, frameworks/keyed/stage0/index.html, frameworks/keyed/stage0/package.json, frameworks/keyed/stage0/rollup.config.js, frameworks/non-keyed/stage0/app.js, frameworks/non-keyed/stage0/index.html, frameworks/non-keyed/stage0/package.json, frameworks/non-keyed/stage0/rollup.config.js
This is VanillaJS implementation using tools from [stage0](https://github.com/Freak613/stage0)
These tools are parts of domc, exported as small functions that can be applied for much more cases.
And what I like in this approach, is its flexibility, while being on VanillaJS level without using any abstractions.
Performance is close to domc, but may be a little worse, so I can't decide whether we should remove domc or leave both.
I hope there is no restrictions on amount of libraries from same author :)
Approach of Vanilla components looks very interesting. This gives another view on how vanilla can be done without usage of frameworks.
=> Added stage0

frameworks/keyed/ko-jsx/package.json, frameworks/keyed/ko-jsx/src/Main.js, frameworks/keyed/ko-jsx/src/template.jsx, frameworks/keyed/solid/package.json, frameworks/keyed/solid/src/main.jsx
Borrowed a page from the Surplus Implementation in how to better handle removing computations for row selection, and borrowed a page from Domc, by rewriting the JSX compiler to output similar cloneNode, and element reference traversal techniques at compile time.
Result is cleaner API, and another drop in memory usage, and build size. Performance is a bit better, although not as much as I hoped locally, but I remain optimistic as on my machine(which is lower powered) nothing every comes close to VanillaJS performance.
Hope you are enjoying your holidays. Cheers.
=> Update SolidJS to 0.1.0 and ko-jsx to 0.1.2

README.md
Small contribution but I love this project and would love to leave my small footprint
=> Added round 8 to README

frameworks/keyed/redom/package.json, frameworks/non-keyed/redom/package.json
- Swap rows should be way faster now!
https://github.com/redom/redom/releases/tag/v3.14.0
=> Update RE:DOM to 3.14

frameworks/keyed/mobx-jsx/index.html, frameworks/keyed/mobx-jsx/package.json, frameworks/keyed/mobx-jsx/rollup.config.js, frameworks/keyed/mobx-jsx/src/main.jsx
More of the same alternate renderer stuff. Experience the power of MobX's fine grained change detection without being restricted by React's VDOM lifecycle. Not quite as performant as the others but still decent. I'm still learning the nuances of MobX but it's a start.
=> Add mobx-jsx implementation

frameworks/keyed/lit-html/package.json, frameworks/keyed/lit-html/src/index.js, frameworks/non-keyed/lit-html/package.json, frameworks/non-keyed/lit-html/src/index.js
Use immutable update pattern with `guard` directive to avoid re-rendering unchanged items
=> Improve lit-html performance

frameworks/keyed/ivi/package.json, frameworks/keyed/ivi/rollup.config.js, frameworks/keyed/ivi/src/main.js
It should significantly reduce memory consumption.
=> Update ivi to 0.16.0

.gitignore, frameworks/keyed/hyperoop/index.html, frameworks/keyed/hyperoop/package.json, frameworks/keyed/hyperoop/rollup.config.js, frameworks/keyed/hyperoop/src/index.tsx, frameworks/keyed/hyperoop/src/rowsView.tsx, frameworks/keyed/hyperoop/src/store.ts, frameworks/keyed/hyperoop/tsconfig.json
Added keyed/hyperoop folder for [hyperoop 0.1.12](https://www.npmjs.com/package/hyperoop)
=> Added keyed/hyperoop

frameworks/keyed/lit-html/package.json, frameworks/non-keyed/lit-html/package.json
=> Update lit-html to v0.14.0

frameworks/keyed/imba/package.json, frameworks/keyed/imba/src/main.imba, frameworks/keyed/imba/webpack.config.js, frameworks/non-keyed/imba/package.json, frameworks/non-keyed/imba/src/main.imba, frameworks/non-keyed/imba/webpack.config.js
Hey. Creator of Imba here. I cleaned up the Imba implementations. Since we're using immutable data here, I also added a simple shouldComponentUpdate-like check in row rendering.
=> Cleanup Imba implementations

frameworks/keyed/rax/index.html, frameworks/keyed/rax/package.json, frameworks/keyed/rax/src/main.jsx, frameworks/keyed/rax/webpack.config.js
Repo: https://github.com/alibaba/rax
=> Add new framework: rax.

frameworks/keyed/lit-html/index.html, frameworks/keyed/lit-html/package.json, frameworks/keyed/lit-html/rollup.config.js, frameworks/keyed/lit-html/src/index.js, frameworks/non-keyed/lit-html/index.html, frameworks/non-keyed/lit-html/package.json, frameworks/non-keyed/lit-html/rollup.config.js, frameworks/non-keyed/lit-html/src/index.js
Improves lit-html performance results
=> Lit-html optimizations

frameworks/keyed/ember/package.json
Seems to have a significant positive effect on render times (given the many iterations)
/cc @NullVoxPopuli
=> Optimize Ember app, to prevent creating unnecessary empty text nodes

frameworks/keyed/lit-html/package.json, frameworks/non-keyed/lit-html/package.json
Sounds like this will be the last RC before release
Also updates build dependencies
=> Update lit-html to 1.0.0-rc.2

frameworks/keyed/lit-html/package.json, frameworks/non-keyed/lit-html/package.json
=> Update lit-html to 1.0.0

frameworks/keyed/lighterhtml/package.json, frameworks/keyed/lighterhtml/rollup.config.js, frameworks/non-keyed/lighterhtml/package.json, frameworks/non-keyed/lighterhtml/rollup.config.js
My deepest apologies but I've realized, after focusing too much on the keyed result, that non-keyed stack was broken, but it has been, fixed right now via https://github.com/WebReflection/lighterhtml/issues/15
Please don't hate me ❤️
=> Update lighterhtml to 0.9.0

frameworks/keyed/react-hooks/index.html, frameworks/keyed/react-hooks/package.json, frameworks/keyed/react-hooks/src/main.jsx, frameworks/keyed/react-hooks/webpack.config.js
Been playing around with Hooks a lot recently.  Super interested how this compares and if we can gain any performance insights. Would appreciate some review.
* I went with single state object since data and selected are mostly updated in unison.
* I used useCallback to only have the single fn ref on appendRows (when rows are added in different renders), but I wouldn't be surprised React.memo is slightly faster on its own.
* I didn't bother splicing array on update, not correct but works. Noticed React implementation doesn't either.
* Did a few less optimized patterns to feel idiomatic like react-redux implementation
=> Adds React Hooks implementation

frameworks/keyed/endorphin/index.html, frameworks/keyed/endorphin/package.json, frameworks/keyed/endorphin/rollup.config.js, frameworks/keyed/endorphin/src/DataStore.js, frameworks/keyed/endorphin/src/app-ui/app-ui.html, frameworks/keyed/endorphin/src/app-ui/app-ui.js, frameworks/keyed/endorphin/src/app.js, frameworks/non-keyed/endorphin/index.html, frameworks/non-keyed/endorphin/package.json, frameworks/non-keyed/endorphin/rollup.config.js, frameworks/non-keyed/endorphin/src/DataStore.js, frameworks/non-keyed/endorphin/src/app-ui/app-ui.html, frameworks/non-keyed/endorphin/src/app-ui/app-ui.js, frameworks/non-keyed/endorphin/src/app.js
Added keyed and non keyed new UI Rendering Library https://github.com/endorphinjs
=> EndorphinJS

frameworks/keyed/redom/package.json, frameworks/non-keyed/redom/package.json
I think this might make a difference: https://github.com/redom/redom/pull/144 😎
=> Update RE:DOM to v3.20.0

frameworks/non-keyed/literaljs/.babelrc, frameworks/non-keyed/literaljs/.gitignore, frameworks/non-keyed/literaljs/index.html, frameworks/non-keyed/literaljs/index.js, frameworks/non-keyed/literaljs/package.json, frameworks/non-keyed/literaljs/store.js
This PR adds LiteralJS nonkeyed.
This is in reference to issue https://github.com/krausest/js-framework-benchmark/issues/545
=> Added literaljs nonkeyed to frameworks

frameworks/keyed/faster-dom/package.json, frameworks/keyed/faster-dom/src/Main.js, frameworks/keyed/faster-dom/src/Store.js
@krausest Hi, was optimize render list(start use fragment) and optimize class supports and remove some unused stuff
=> Faster-dom - Optimize call, use version with fragment support

frameworks/keyed/san/package.json, frameworks/keyed/san/src/App.js, frameworks/non-keyed/san/package.json, frameworks/non-keyed/san/src/App.js, frameworks/non-keyed/san/src/store.es6.js
The following changes has been made:
- update san version to 3.7.5
- add `autoFillStyleAndId` property
- use for instanceof forEach
=> Update san to 3.7.5

frameworks/keyed/react-redux/src/main.jsx
1. Reimplemented with a [react-redux hooks API](https://react-redux.js.org/next/api/hooks)
2. Modified state mutations to make sure that it is implemented in a similar way as `lit-html` (they've changed it in one of the latest pull requests and I am just trying to reduce differences)
=> Switch to hooks API in react-redux

frameworks/keyed/ko-jsx/src/template.jsx, frameworks/keyed/mobx-jsx/src/main.jsx, frameworks/keyed/solid/src/main.jsx
As per #578 this adds missing attribute to these libraries.
=> Add aria-hidden to Solid, mobx-jsx, and ko-jsx

frameworks/keyed/sinuous/package.json, frameworks/keyed/sinuous/src/main.js
Adds the `aria-hidden` attribute to the remove span element.
#578
=> Add aria-hidden to Sinuous

frameworks/keyed/sinuous/package.json, frameworks/keyed/sinuous/src/main.js
- Added small optimizations and reduced bundle size.
- Removed legacy `observable` library support
https://github.com/dominictarr/observable
=> Update Sinuous v0.9.0

frameworks/keyed/glimmer/.template-lintrc.js, frameworks/keyed/glimmer/config/targets.js, frameworks/keyed/glimmer/package.json, frameworks/keyed/glimmer/src/main.ts, frameworks/keyed/glimmer/src/ui/components/Glimmer/component-test.ts, frameworks/keyed/glimmer/src/ui/components/Glimmer/component.ts, frameworks/keyed/glimmer/src/ui/components/Glimmer/template.hbs, frameworks/keyed/glimmer/src/ui/components/PerformantEach/component.ts, frameworks/keyed/glimmer/src/ui/components/PerformantEach/template.hbs, frameworks/keyed/glimmer/src/ui/components/Row/template.hbs, frameworks/keyed/glimmer/src/ui/components/Table/template.hbs, frameworks/keyed/glimmer/src/ui/components/eq/helper-test.ts, frameworks/keyed/glimmer/src/ui/components/eq/helper.ts
Should be at least 5x performant on row swaps, due to https://github.com/glimmerjs/glimmer-vm/pull/945
=> glimmer update (perf improvements)

frameworks/keyed/domvm/build.js, frameworks/keyed/domvm/package.json, frameworks/keyed/domvm/src/main.es6.js, frameworks/non-keyed/domvm/build.js, frameworks/non-keyed/domvm/package.json, frameworks/non-keyed/domvm/src/main.es6.js, results-ui/package.json, results-ui/src/bootstrap-reboot.css, results-ui/src/build.js, results-ui/src/style.css
been a while. v3.4.12 looks a bit faster overall on my machine.
=> update domvm & results-ui

frameworks/keyed/attodom/package.json, frameworks/keyed/attodom/src/view.js
Minor update to bring it up to the latest 12.0.0 version and to make the selection "more direct" like other implementation.
This is more of a library than a framework so I have no issues if it is deemed not relevant to this benchmark.
As before, the first design goal is to have a light and efficient implementation that is backward compatible with older browsers and phones.
Merci!
=> 12.0.0 and row selection

frameworks/keyed/endorphin/package.json, frameworks/non-keyed/endorphin/package.json
Updated `endorphin` lib to v0.5.1
=> Endorphin v0.5.1

frameworks/keyed/reason-react/.gitignore, frameworks/keyed/reason-react/bsconfig.json, frameworks/keyed/reason-react/package.json, frameworks/keyed/reason-react/src/Button.re, frameworks/keyed/reason-react/src/Jumbotron.re, frameworks/keyed/reason-react/src/Main.re, frameworks/keyed/reason-react/src/Row.re
The JSX Record API for Reason React is deprecated
https://reasonml.github.io/reason-react/docs/en/jsx-2
=> Migrate to reason jsx 3

frameworks/keyed/sinuous/package.json
Shouldn't affect performance too much, might be a bit faster because
- `map` uses an Array instead of Map to keep track of the disposers
- in `map` full replace used to use a loop of `removeChild` calls instead of a simple `.textContent = ''` to clear which is possible since there are no sibling elements.
- Fixed naming issue for umd and iife bundles
- Add observable duplicate edges check
- Replace Map w/ array for `map` disposers
- Fixed [Plain array in root doesn't return `DocumentFragment` #19](https://github.com/luwes/sinuous/issues/19)
- Fixed [template` inserts with duplicate value are empty #14](https://github.com/luwes/sinuous/issues/14)
- Fixed [Incorrect updating of observable #18](https://github.com/luwes/sinuous/issues/18)
- Upgraded `sinuous/htm` and …
=> Update Sinuous v0.12.6

frameworks/keyed/crui/index.html, frameworks/keyed/crui/package.json, frameworks/keyed/crui/src/app.ts, frameworks/keyed/crui/src/jumbotron.ts, frameworks/keyed/crui/src/main.ts, frameworks/keyed/crui/src/store.ts, frameworks/keyed/crui/src/table.ts, frameworks/keyed/crui/src/utils.ts, frameworks/keyed/crui/tsconfig.json, frameworks/keyed/crui/webpack.config.js
Add a benchmark for CRUI library. I hope it was correct to put it in "non-keyed", but please be aware that this lib do not use a VDOM, so the keyed concept doesn't really matter.
=> CRUI benchmark

frameworks/keyed/riot/package.json, frameworks/non-keyed/riot/package.json
=> Update Riot.js version

frameworks/keyed/mikado/package.json, frameworks/non-keyed/mikado/package.json
I discovered some overhead in the render pipeline. This is fixed in v0.0.7, although it is not very urgent.
=> Update Mikado Version

frameworks/keyed/mikado/index.html, frameworks/keyed/mikado/package.json, frameworks/keyed/mikado/src/main.js, frameworks/keyed/mikado/src/template/item.html, frameworks/keyed/mikado/task/build.js, frameworks/non-keyed/mikado/index.html, frameworks/non-keyed/mikado/package.json, frameworks/non-keyed/mikado/src/main.js, frameworks/non-keyed/mikado/src/template/item.html, frameworks/non-keyed/mikado/task/build.js
Sorry I could not re-open the old pull request ...
=> Update Mikado to v0.6.5

frameworks/keyed/mikado-proxy/index.html, frameworks/keyed/mikado-proxy/package.json, frameworks/keyed/mikado-proxy/src/data.js, frameworks/keyed/mikado-proxy/src/main.js, frameworks/keyed/mikado-proxy/src/template/app.html, frameworks/keyed/mikado-proxy/src/template/item.html, frameworks/keyed/mikado-proxy/task/build.js
This is a 100% reactive data-driven approach. It uses Mikados __proxy__ and the new feature __observable array__ (Virtual NodeList) under the hood. Also this one might be the smallest and most simple implementation on the table. Technically it completely differs from my other implementation, so it would be really nice to see both paradigm compared :)
=> ADD mikado-proxy

frameworks/keyed/lighterhtml/package.json, frameworks/keyed/lighterhtml/rollup.config.js, frameworks/keyed/lighterhtml/src/index.js, frameworks/non-keyed/lighterhtml/package.json, frameworks/non-keyed/lighterhtml/rollup.config.js, frameworks/non-keyed/lighterhtml/src/index.js
The [lighterhtml](https://github.com/WebReflection/lighterhtml#readme) library reached version 2.
This MR would like to have it updated so that tests would be more aligned with current performance.
Thank you.
=> Update lighterhtml to v2

frameworks/keyed/lighterhtml/package.json, frameworks/keyed/lighterhtml/src/index.js, frameworks/non-keyed/lighterhtml/package.json, frameworks/non-keyed/lighterhtml/src/index.js
As I've found _domc_ implementation both clean and elegant, and as I wanted to also cleanup the previous test, I'd like to update current _hyperhtml_ test which also slightly improves the select row performance.
Thanks for your patience, and the eventual update, I promise this time I've already tested current changes and everything runs smoothly.
Best Regards.
=> lighterhtml: update test using the domc implementation

frameworks/keyed/neverland/index.html, frameworks/keyed/neverland/package.json, frameworks/keyed/neverland/rollup.config.js, frameworks/keyed/neverland/src/index.js, frameworks/keyed/neverland/src/utils.js, frameworks/non-keyed/neverland/index.html, frameworks/non-keyed/neverland/package.json, frameworks/non-keyed/neverland/rollup.config.js, frameworks/non-keyed/neverland/src/index.js, frameworks/non-keyed/neverland/src/utils.js
The [neverland](https://github.com/WebReflection/neverland/#readme) project just reached its 3rd major update.
Even if I know it cannot be faster than _lighterhtml_, I'd like to add this library to the list of tests.
Thanks for considering this PR.
=> neverland: hooks for lighterhtml

frameworks/keyed/heresy/package.json, frameworks/keyed/heresy/src/index.js, frameworks/keyed/heresy/src/ui/app.js, frameworks/keyed/heresy/src/ui/row.js, frameworks/non-keyed/heresy/package.json, frameworks/non-keyed/heresy/src/index.js, frameworks/non-keyed/heresy/src/ui/app.js, frameworks/non-keyed/heresy/src/ui/row.js
For all the exact same reasons specified in #676, this is the ultimate change to drop WeakMap slowdown from the equation.
This change also brings in the very latest version of the library, which includes all core updates.
=> heresy: final test-case + version update

frameworks/keyed/hyperhtml/index.html, frameworks/keyed/hyperhtml/package.json, frameworks/keyed/hyperhtml/rollup.config.js, frameworks/keyed/hyperhtml/src/index.js, frameworks/keyed/hyperhtml/src/row.js
For all the exact same reasons specified in https://github.com/krausest/js-framework-benchmark/pull/676, this is the ultimate change to drop `WeakMap` slowdown from the equation.
=> hyperhtml: final test-case update

frameworks/keyed/riot/package.json, frameworks/non-keyed/riot/package.json
Merry Christmas and Happy new Year 🎉
=> Update Riot.js to v4.8.0

frameworks/keyed/vue-next/package.json, frameworks/keyed/vue-next/src/App.vue, frameworks/non-keyed/vue-next/package.json, frameworks/non-keyed/vue-next/src/App.vue
Refactor vue-next tests with composition api and update to alpha 5.
(In my local iterations there are some improvements from #691)
=> Refactor vue-next with composition api

frameworks/keyed/riot/package.json, frameworks/keyed/riot/src/app.riot, frameworks/non-keyed/riot/package.json, frameworks/non-keyed/riot/src/app.riot
This PR optimizes the click events using the same technique used in the Vue.js Benchmark
=> Simplify click events and update Riot.js

frameworks/keyed/domdiff/package.json, frameworks/keyed/heresy/package.json, frameworks/keyed/hyperhtml/package.json, frameworks/keyed/lighterhtml/package.json, frameworks/keyed/neverland/package.json, frameworks/keyed/uhtml/package.json, frameworks/non-keyed/domdiff/package.json, frameworks/non-keyed/heresy/package.json, frameworks/non-keyed/lighterhtml/package.json, frameworks/non-keyed/neverland/package.json, frameworks/non-keyed/uhtml/package.json, webdriver-ts/src/isKeyed.ts
There have been quite some consistent refactoring of my libraries so that I've thought it might make sense to update all their score/benchmarks at once.
=> Fix #708 - Updated lighterhtml, neverland, heresy, uhtml & hyperhtml

frameworks/keyed/lit-element/index.html, frameworks/keyed/lit-element/package.json, frameworks/keyed/lit-element/rollup.config.js, frameworks/keyed/lit-element/src/main.ts, frameworks/keyed/lit-element/src/store.ts, frameworks/keyed/lit-element/tsconfig.json, frameworks/non-keyed/lit-element/index.html, frameworks/non-keyed/lit-element/package.json, frameworks/non-keyed/lit-element/rollup.config.js, frameworks/non-keyed/lit-element/src/main.ts, frameworks/non-keyed/lit-element/src/store.ts, frameworks/non-keyed/lit-element/tsconfig.json
Benchmarks for lit-element was missing from the frameworks, only lit-html existed.
Would be great to add this framework too.
=> Added benchmarks for lit-element

frameworks/keyed/isotope/index.html, frameworks/keyed/isotope/package.json, frameworks/keyed/isotope/rollup.config.js, frameworks/keyed/isotope/src/main.js, frameworks/keyed/isotope/src/menu.js, frameworks/keyed/isotope/src/utils.js
Hi there!
First off, great thanks for this benchmark - I've been using it as a reference and performance comparison resource for a long time now!
With this PR, I'd like to add my new open-source UI library called **Isotope** to the comparison. If you're interested, the repo for the library is [here](https://github.com/Isotope-js/core), and the docs [here](https://areknawo.com/isotope).
=> Add Isotope UI library

frameworks/keyed/riot/package.json, frameworks/keyed/riot/src/app.riot, frameworks/non-keyed/riot/package.json, frameworks/non-keyed/riot/src/app.riot
I wasn't happy about this PR https://github.com/krausest/js-framework-benchmark/pull/707, I felt like cheating (even if other frameworks use this cheap cheat to improve their performance)
I was able to solve the problem to  the root improving the way Riot.js handles its events internally.
=> Riot.js improved event handling

frameworks/keyed/helix/.clj-kondo/config.edn, frameworks/keyed/helix/.gitignore, frameworks/keyed/helix/index-dev.html, frameworks/keyed/helix/index.html, frameworks/keyed/helix/package.json, frameworks/keyed/helix/shadow-cljs.edn, frameworks/keyed/helix/src/demo/main.cljs, frameworks/keyed/helix/src/demo/utils.cljs
[Helix](https://github.com/Lokeh/helix) is a react wrapper library for ClojureScript which tries to provide as much of original react to cljs as possible.
The demo code is ported from frameworks/keyed/reagent
=> add helix framework

frameworks/keyed/doz/index.html, frameworks/keyed/doz/package.json, frameworks/keyed/doz/src/index.js
Hi, I would like to add my framework. I am aware that it may not be fast but I would like to improve it. Thank you so much.
=> add Doz keyed

frameworks/keyed/doz/package.json, frameworks/non-keyed/doz/index.html, frameworks/non-keyed/doz/package.json, frameworks/non-keyed/doz/src/index.js
This PR update the version to 3.0.1 and inclues non-keyed test. I still apologize for the previous PR.. -.-"
=> Add Doz non-keyed with new version

frameworks/keyed/dojo/src/App.ts, frameworks/keyed/dojo/src/RowContainer.ts, frameworks/keyed/dojo/src/Store.ts
A couple of tweaks to hopefully improve the results in a couple of the benchmark tests.
=> Dojo: Improve the dojo keyed implementation

frameworks/keyed/vue2-composition-api/.babelrc, frameworks/keyed/vue2-composition-api/index.html, frameworks/keyed/vue2-composition-api/package.json, frameworks/keyed/vue2-composition-api/src/App.vue, frameworks/keyed/vue2-composition-api/src/main.es6.js, frameworks/keyed/vue2-composition-api/webpack.config.js
[@vue/composition-api](https://github.com/vuejs/composition-api) is the official plugin for Vue 2 to support Vue 3's Composition API. 
Adding this framework to the benchmarks is mainly for users to know its extra costs.
Thanks.
=> Add @vue/composition-api

frameworks/keyed/san/package.json, frameworks/non-keyed/san/package.json
=> update san to 3.9.0, for #694

frameworks/keyed/crank/index.html, frameworks/keyed/crank/package.json, frameworks/keyed/crank/src/main.jsx, frameworks/keyed/crank/webpack.config.js
Please don’t merge or run the benchmarks yet!
This is a work in progress and it only doesn’t run like ass on a development branch of Crank.js. I need to deploy a release with performance fixes!
Thanks for creating this project. It was super helpful for finding performance problems and watching the benchmarks run was equal parts nerve-racking and exciting. I’ll have more thoughts on what I think about the benchmarks soon!
=> Add Crank.js

frameworks/keyed/fullweb-helpers/index.html, frameworks/keyed/fullweb-helpers/package.json, frameworks/keyed/fullweb-helpers/rollup.config.js, frameworks/keyed/fullweb-helpers/src/index.js, frameworks/keyed/fullweb-helpers/tsconfig.json, frameworks/keyed/fullweb-template/index.html, frameworks/keyed/fullweb-template/package.json, frameworks/keyed/fullweb-template/rollup.config.js, frameworks/keyed/fullweb-template/src/index.js, frameworks/keyed/fullweb-template/tsconfig.json
Small helpers library to demonstrate some of the stuff I learned thanks to this project.
Check https://github.com/fullwebdev/fullwebdev/tree/master/packages/helpers for the source.
=> add @fullweb/helpers 0.1.0 implementations

frameworks/keyed/doz/package.json, frameworks/keyed/doz/src/index.js, frameworks/non-keyed/doz/package.json, frameworks/non-keyed/doz/src/index.js
Hi, in this release I have rewritten much of the template engine. Should improve a little.
=> update Doz to 3.4.0

frameworks/keyed/doz/package.json, frameworks/non-keyed/doz/package.json, frameworks/non-keyed/doz/src/index.js
This update improve non-keyed performance... maybe even for keyed!
=> update Doz to 3.4.1

frameworks/keyed/react-tracked/index.html, frameworks/keyed/react-tracked/package-lock.json, frameworks/keyed/react-tracked/package.json, frameworks/keyed/react-tracked/src/main.jsx, frameworks/keyed/react-tracked/webpack.config.js
https://react-tracked.js.org
---
The src/main.jsx is based on react-redux-hooks and react-hooks.
=> Add react tracked

frameworks/keyed/hyperapp/package.json, frameworks/keyed/hyperapp/src/index.js
This pull request updates the hyperapp entry to support the latest syntax changes and improvements as of 2.0.8.
=> Update hyperapp (syntax) to 2.0.8

frameworks/keyed/preact/.babelrc, frameworks/keyed/preact/package-lock.json, frameworks/keyed/preact/package.json, frameworks/keyed/preact/src/Main.jsx, frameworks/keyed/preact/src/Row.jsx, frameworks/keyed/reaml-preact/package-lock.json, frameworks/keyed/reaml-preact/package.json
I'm seeing some impressive improvements: in my local run, the slowdown before this PR = 1.34, after = 1.26!
=> keyed/preact: update preact to 10.5.2

frameworks/keyed/etch/.babelrc, frameworks/keyed/etch/babel.config.js, frameworks/keyed/etch/index.html, frameworks/keyed/etch/package-lock.json, frameworks/keyed/etch/package.json, frameworks/keyed/etch/src/Main.jsx, frameworks/keyed/etch/src/Row.jsx, frameworks/keyed/etch/src/Store.es6.js, frameworks/keyed/etch/src/main.es6.js, frameworks/keyed/etch/webpack.config.js, frameworks/non-keyed/etch/babel.config.js, frameworks/non-keyed/etch/index.html, frameworks/non-keyed/etch/package-lock.json, frameworks/non-keyed/etch/package.json, frameworks/non-keyed/etch/src/Main.jsx, frameworks/non-keyed/etch/src/Row.jsx, frameworks/non-keyed/etch/src/Store.es6.js, frameworks/non-keyed/etch/src/main.es6.js, frameworks/non-keyed/etch/webpack.config.js
This adds etch back which has become active again:
https://github.com/atom/etch
Fixes: https://github.com/atom/etch/issues/87
=> Add etch benchmark (revive)

frameworks/keyed/alpine/index.html, frameworks/keyed/alpine/package-lock.json, frameworks/keyed/alpine/package.json, frameworks/keyed/alpine/rollup.config.js, frameworks/keyed/alpine/src/main.js
Given it's popularity over the past year I figured this was a good inclusion. https://github.com/alpinejs/alpine
Unfortunately the runtime isn't tree-shakeable (built primarily for CDN) so it doesn't tell it's size story as well more optimized build processes I think it's fair.
I've been having some issues running the tests locally though and I want to know if you experience the same. It seems that after the first click things stop tracking. It's strange since the library is pretty simplistic API-wise so not sure about the cause of this behavior.
I will make an issue on their repo too to see if they have any ideas. But the library looks really straight forward to use.
=> Add alpine keyed

frameworks/keyed/mikado/package-lock.json, frameworks/keyed/mikado/package.json, frameworks/keyed/mikado/src/data.js, frameworks/keyed/mikado/src/main.js, frameworks/keyed/mikado/src/template/item.html, frameworks/keyed/mikado/task/build.js, frameworks/non-keyed/mikado/package-lock.json, frameworks/non-keyed/mikado/package.json, frameworks/non-keyed/mikado/src/data.js, frameworks/non-keyed/mikado/src/main.js, frameworks/non-keyed/mikado/src/template/item.html, frameworks/non-keyed/mikado/task/build.js
Passed Issues Keyed:
Passed Issues Non-Keyed:
=> update Mikado to latest + fix issues

frameworks/keyed/react-rxjs/index.html, frameworks/keyed/react-rxjs/package-lock.json, frameworks/keyed/react-rxjs/package.json, frameworks/keyed/react-rxjs/src/main.jsx, frameworks/keyed/react-rxjs/webpack.config.js
Hi @krausest,
Would it be possible to add react-rxjs?
Thanks,
=> add react-rxjs

frameworks/keyed/glimmer-2/src/MyTable.ts, frameworks/keyed/glimmer-2/src/TableRow.ts, frameworks/keyed/glimmer-2/src/utils/benchmark-helpers.ts, frameworks/keyed/glimmer-2/src/utils/helper.ts
related to https://github.com/krausest/js-framework-benchmark/pull/786
=> bugfix: glimmer-2 issue #800

frameworks/keyed/react-redux-hooks-immutable/index.html, frameworks/keyed/react-redux-hooks-immutable/package-lock.json, frameworks/keyed/react-redux-hooks-immutable/package.json, frameworks/keyed/react-redux-hooks-immutable/src/main.jsx, frameworks/keyed/react-redux-hooks-immutable/webpack.config.js
Was just curious to see how redux + immutable.js performs
=> add react redux + immutable

frameworks/keyed/ember/app/components/my-table.js, frameworks/keyed/ember/app/helpers/eq.js, frameworks/keyed/ember/app/services/state.js, frameworks/keyed/ember/app/templates/components/my-table.hbs, frameworks/keyed/ember/tests/unit/services/state-test.js
related https://github.com/krausest/js-framework-benchmark/pull/821
=> Ember 800 improvements

frameworks/keyed/fractal/.babelrc, frameworks/keyed/fractal/.gitignore, frameworks/keyed/fractal/.prettierrc, frameworks/keyed/fractal/index.html, frameworks/keyed/fractal/package-lock.json, frameworks/keyed/fractal/package.json, frameworks/keyed/fractal/src/main.tsx, frameworks/keyed/fractal/tsconfig.json, frameworks/keyed/fractal/webpack.config.js, frameworks/non-keyed/fractal/.babelrc, frameworks/non-keyed/fractal/.gitignore, frameworks/non-keyed/fractal/.prettierrc, frameworks/non-keyed/fractal/index.html, frameworks/non-keyed/fractal/package-lock.json, frameworks/non-keyed/fractal/package.json, frameworks/non-keyed/fractal/src/main.tsx, frameworks/non-keyed/fractal/tsconfig.json, frameworks/non-keyed/fractal/webpack.config.js
Hi @krausest )
Would it be possible to add my framework?
Thanks
=> Add fractal implementation

frameworks/keyed/react-tracked/package-lock.json, frameworks/keyed/react-tracked/package.json, frameworks/keyed/react-tracked/src/main.jsx
also follows the change in #831.
=> update react-tracked v1.6.0

frameworks/keyed/valtio/index.html, frameworks/keyed/valtio/package-lock.json, frameworks/keyed/valtio/package.json, frameworks/keyed/valtio/src/main.jsx, frameworks/keyed/valtio/webpack.config.js
https://github.com/pmndrs/valtio
=> add valtio

frameworks/keyed/react-redux-rematch/index.html, frameworks/keyed/react-redux-rematch/package-lock.json, frameworks/keyed/react-redux-rematch/package.json, frameworks/keyed/react-redux-rematch/src/main.jsx, frameworks/keyed/react-redux-rematch/webpack.config.js
Hi! 👋 ,
I'm Sergio Moreno, lead maintainer of [Rematch](https://rematchjs.org), I've been working on a v2.0.0 version with a lot of new improvements and wanted to checked that the difference with Redux in terms of performance is ridiculous but the maintainability and the steep curve was reduced.
I've correctly run the suite on my local machine:
Feel free rquest any changes =)
=> feat: introduced rematch framework

frameworks/keyed/ko-jsx/package-lock.json, frameworks/keyed/ko-jsx/package.json, frameworks/keyed/ko-jsx/src/Main.js, frameworks/keyed/ko-jsx/src/template.jsx, frameworks/keyed/mobx-jsx/package-lock.json, frameworks/keyed/mobx-jsx/package.json, frameworks/keyed/mobx-jsx/rollup.config.js, frameworks/keyed/mobx-jsx/src/main.jsx, frameworks/keyed/vuerx-jsx/package-lock.json, frameworks/keyed/vuerx-jsx/package.json, frameworks/keyed/vuerx-jsx/src/main.jsx
This PR adds Solid's optimization around selection to the other reactive libraries based on my DOM Expressions renderer. While it isn't quite the same mechanism I'm hoping it restores these libraries to some of their former glory. There is a steeper memory cost here but I'm hoping performance is worth it.
=> Update MobX JSX, VueRX JSX, and KO JSX

frameworks/keyed/valtio/package-lock.json, frameworks/keyed/valtio/package.json, frameworks/keyed/valtio/src/main.jsx
=> chore: update valtio

frameworks/keyed/react-hooks/package-lock.json, frameworks/keyed/react-hooks/package.json, frameworks/keyed/react-hooks/src/main.jsx, frameworks/keyed/react-hooks/webpack.config.js, frameworks/keyed/react/.vscode/settings.json, frameworks/keyed/react/package-lock.json, frameworks/keyed/react/package.json, frameworks/keyed/react/src/main.jsx, frameworks/keyed/react/webpack.config.js
it PR slightly increase react-hooks performance (useCallback is missing in current implementation), and rewrite react with classes - now react-hooks and react implementations are same - first use memo, useReducer and useCallback, second use PureComponent, state and methods (one dispatch instead of one method per action)
react-hooks performance are great, and react with classes so slow. hooks:classes - 1:0
=> Update react and react-hooks

frameworks/keyed/svelte/package-lock.json, frameworks/keyed/svelte/package.json, frameworks/keyed/svelte/src/Main.svelte, frameworks/non-keyed/svelte/package-lock.json, frameworks/non-keyed/svelte/package.json, frameworks/non-keyed/svelte/src/Main.svelte
Upgrade to svelte 3.37.0 & add sub millisecond performance enhancement to buildData.
=> Svelte 3.37.0

frameworks/keyed/fntags/build.js, frameworks/keyed/fntags/package-lock.json, frameworks/keyed/fntags/package.json
Fixes #892
Sorry for the delay, was on vacation
=> fntags moved to the srfnstack org, this update fixes that.

frameworks/keyed/vue/package.json, frameworks/non-keyed/vue/package.json
=> update to VueJs 3.1.1

frameworks/keyed/alpine/package-lock.json, frameworks/keyed/alpine/package.json, frameworks/keyed/alpine/src/main.js
Alpine now uses Vue 3 reactivity. Seems to be way faster.
=> Update Alpine to V3

frameworks/keyed/ls-element/index.html, frameworks/keyed/ls-element/package-lock.json, frameworks/keyed/ls-element/package.json, frameworks/keyed/ls-element/src/main.tsx, frameworks/keyed/ls-element/webpack.config.js
With this update performance was improved and syntax changed.
Cheers!
=> Update LS-Element version

frameworks/keyed/crank/package-lock.json, frameworks/keyed/crank/package.json, frameworks/keyed/crank/src/main.jsx
Haven’t run this locally, but I’m curious to see if anything has improved or degraded.
=> Update crank to 0.4.1

frameworks/keyed/react-lab/index.html, frameworks/keyed/react-lab/package-lock.json, frameworks/keyed/react-lab/package.json, frameworks/keyed/react-lab/src/main.jsx, frameworks/keyed/react-lab/webpack.config.js
"[React Lab](https://github.com/guojin-long/react-lab)" is an experimental branch of React that focuses on performance optimization.
=> add keyed react-lab

frameworks/keyed/lwc/index.html, frameworks/keyed/lwc/lwc.config.json, frameworks/keyed/lwc/package-lock.json, frameworks/keyed/lwc/package.json, frameworks/keyed/lwc/rollup.config.js, frameworks/keyed/lwc/src/bench/app/app.html, frameworks/keyed/lwc/src/bench/app/app.js, frameworks/keyed/lwc/src/index.js
This adds the [LWC](https://lwc.dev/) (Lightning Web Components) framework to the benchmark. I've run `rebuild-check-single.js` and it seems to be correct.
BTW thank you for maintaining this project!
=> Add new framework: LWC

webdriver-ts/package.json
This fixes issue with lighthouse stuck forever after any benchmark.
=> FIx #975 - Update lighthouse package version

frameworks/keyed/malina/.gitignore, frameworks/keyed/malina/README.md, frameworks/keyed/malina/index.html, frameworks/keyed/malina/package-lock.json, frameworks/keyed/malina/package.json, frameworks/keyed/malina/rollup.config.js, frameworks/keyed/malina/src/App.xht, frameworks/keyed/malina/src/main.js
Implementation for [Malina.js](https://github.com/malinajs/malinajs)
=> Add Malina.js keyed

frameworks/keyed/react-zustand/src/main.jsx
This PR updates the Zustand implementation following the recommendations by @oleggrishechkin (https://github.com/krausest/js-framework-benchmark/pull/973#issuecomment-1002744463)
=> Update Zustand implementation

frameworks/keyed/xania/index.html, frameworks/keyed/xania/package-lock.json, frameworks/keyed/xania/package.json, frameworks/keyed/xania/src/app.tsx, frameworks/keyed/xania/src/table-store.ts, frameworks/keyed/xania/tsconfig.json, frameworks/keyed/xania/webpack.config.js, package.json
Alpha version of xaniajs framework joining the benchmark
=> xaniajs framework

webdriver-ts/src/isKeyed.ts
* Fix non-keyed test for remove. result.removedStoredTr checks any count
greater than 0. removeStoredTr represents any <tr> node in target
'table.table'. Removing row two <tr>, index 1, means removedStoredTr
will be 1 based on target, which results in an invalid error message.
Now the <tr> node to be removed is ignored.
Invalid error message received:
```
Non-keyed test for remove failed. Expected that the dom node for the 2nd row would NOT be removed, but it was.
```
Expected:
Non-keyed frameworks pass non-keyed remove test.
Tested with various non-keyed frameworks on master commit f1ea4bb5c64c752979778bb10620c1ebe1c46a85.
riot before:
```
Non-keyed test for remove failed. Expected that the dom node for the 2nd row would NOT be removed, but it was.
riot-v5.3.0-non-keyed is non-keyed for …
```
=> Fix non-keyed test for remove

frameworks/keyed/sinuous/package-lock.json, frameworks/keyed/sinuous/package.json
This upgrades Sinuous to the latest version with a perf fix 🤞
https://github.com/luwes/sinuous/commit/2a4345ccf878a90648447d05318154fb4ddb321e
=> Upgrade Sinuous 0.28.1

frameworks/non-keyed/slingjs/index.html, frameworks/non-keyed/slingjs/package-lock.json, frameworks/non-keyed/slingjs/package.json, frameworks/non-keyed/slingjs/src/controller.js, frameworks/non-keyed/slingjs/src/main.es6.js
* Update Sling.js to version 14.0.0.
=> Implement benchmark using Sling.js 14.0.0

frameworks/keyed/voby/index.html, frameworks/keyed/voby/package.json, frameworks/keyed/voby/src/main.tsx
Hey there, I just published a new little framework, [`voby`](https://github.com/fabiospampinato/voby).
Here's the keyed implementation for it.
I'm very curious to see how it compares with the rest in the benchmark!
=> Implemented Voby-keyed

frameworks/non-keyed/slingjs/index.html, frameworks/non-keyed/slingjs/package-lock.json, frameworks/non-keyed/slingjs/package.json, frameworks/non-keyed/slingjs/src/controller.js
* Update to Sling.js version 14.3.0.
=> Update to Sling.js version 14.3.0

frameworks/keyed/voby/package.json
I added a handful of extra optimizations, overall not much should change I think.
=> Updated Voby to v0.12.0

frameworks/keyed/voby/package.json, frameworks/keyed/voby/src/main.tsx
A few more optimizations here and there, but most importantly I've replaced the model implementation with a much cleaner one, it's basically copied from Solid.
I think it would be interesting to see both implementations in the benchmark potentially, the clean one and the hand-optimized one that still doesn't mess with the DOM manually or do other flagged stuff. @krausest if you think it'd be appropriate to have two implementations for this framework, a clean one and one that squeezes every possible drop of performance out of it, then I'll submit both, otherwise it's probably better to keep the clean one only in here.
Sorry for the many PRs in close succession I've submitted so far, this might be the last for a while.
=> Updated Voby to v0.16

frameworks/keyed/forgo/index.html, frameworks/keyed/forgo/package-lock.json, frameworks/keyed/forgo/package.json, frameworks/keyed/forgo/src/main.tsx, frameworks/keyed/forgo/tsconfig.json
This PR adds support for [ForgoJS](https://forgojs.org/) at version 2.2.3.
=> Added support for ForgoJS

frameworks/keyed/react-hooks/package-lock.json, frameworks/keyed/react-hooks/package.json, frameworks/keyed/react-hooks/src/main.jsx
In my local tests pure react18 solution faster than react17 and event faster than other react implementations,
React with some external state management slower (clear rows much slower, maybe useEffect affected in new react18, useSyncExternalStore has the same performance as forceUpdate with direct subscribing in useEffect)
=> Update react to 18

frameworks/keyed/karyon/index.html, frameworks/keyed/karyon/package-lock.json, frameworks/keyed/karyon/package.json, frameworks/keyed/karyon/rollup.config.js, frameworks/keyed/karyon/src/main.js
Implementation for [Karyon](https://github.com/karyonjs/karyon)
=> Add Karyon keyed

frameworks/keyed/uhtml/package-lock.json, frameworks/keyed/uhtml/package.json, frameworks/non-keyed/uhtml/package-lock.json, frameworks/non-keyed/uhtml/package.json
[µhtml](https://github.com/WebReflection/uhtml#readme) has landed with smaller size, modern code, and overall better performance, so I'd love to have it updated in here too, thank you 🙏
=> Update uhtml to version 3

frameworks/non-keyed/art/index.html, frameworks/non-keyed/art/package-lock.json, frameworks/non-keyed/art/package.json, frameworks/non-keyed/art/src/main.jsx, frameworks/non-keyed/art/vite.config.js
=> Added support for Art

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json, frameworks/keyed/voby/src/main.tsx
A huuuuge amount of improvements have been made:
- The underlying algorithm for the reactivity system is much more similar to MobX's, which improves performance significantly under real scenarios.
- The exposed interface is significantly cleaner, a lot of redundant or not useful enough stuff got deleted.
- A basic Suspense implementation got implemented.
- A more optimized clearing algorithm got implemented.
- A decent amount of internal bugs has been fixed.
Unfortunately it seems that at least locally some of these optimizations and changes worsened performance in the benchmark, maybe the added overhead can be trimmed away, I haven't looked into that yet.
=> Updated Voby to v0.18

frameworks/keyed/react-redux-hooks/package-lock.json, frameworks/keyed/react-redux-hooks/package.json, frameworks/keyed/react-redux-hooks/src/main.jsx
I just updated deps, but I think we should use @reduxjs/toolkit, because it's official "true" way of using redux. What do you think?
=> Update react-redux to 8.0.1

frameworks/keyed/karyon/package-lock.json, frameworks/keyed/karyon/package.json
An update to the latest version of [karyon](https://www.npmjs.com/package/karyon) library.
=> Update karyon to v1.0.10

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json
Some important internal changes and fixes. Nothing that seems to have any impact on the benchmark though. Though I'm seeing weird memory usage numbers being reported locally.
=> Updated Voby to v0.21.1

frameworks/keyed/react-lab/src/main.jsx
=> Update to the same implementation as keyed/react-hooks

frameworks/keyed/jotai/package-lock.json, frameworks/keyed/jotai/package.json, frameworks/keyed/valtio/package-lock.json, frameworks/keyed/valtio/package.json
Should I update react/react-dom too?
=> update keyed/jotai and keyed/valtio

frameworks/keyed/karyon/package-lock.json, frameworks/keyed/karyon/package.json
An update to the latest version of [karyon](https://www.npmjs.com/package/karyon) library.
=> Update karyon to v1.1.3

frameworks/keyed/mahal/package-lock.json, frameworks/keyed/mahal/package.json
=> update mahal version to 1.3.4

frameworks/keyed/react-rxjs/package-lock.json, frameworks/keyed/react-rxjs/package.json, frameworks/keyed/react-rxjs/src/main.jsx
Upgrading react-rxjs from 0.6.0 to 0.9.8. A few things have been changed since then, and it should yield some better results.
=> Update react-rxjs to 18.2.0+0.9.8

frameworks/keyed/whatsup/.babelrc, frameworks/keyed/whatsup/package-lock.json, frameworks/keyed/whatsup/package.json, frameworks/keyed/whatsup/src/main.tsx, frameworks/keyed/whatsup/src/store.ts, frameworks/keyed/whatsup/tsconfig.json
Hi @krausest
Please take a look at this when you have time.
=> update whatsup version & implementation

frameworks/keyed/reflex/.babelrc, frameworks/keyed/reflex/.gitignore, frameworks/keyed/reflex/index.html, frameworks/keyed/reflex/package-lock.json, frameworks/keyed/reflex/package.json, frameworks/keyed/reflex/src/main.jsx, frameworks/keyed/reflex/tsconfig.json, frameworks/keyed/reflex/webpack.config.js
Should work now ! Not touching repo until validated or tested.
It have the minimum dependencies possible, to install and test / bench it :
```bash
cd frameworks/keyed/reflex
npm i
npm run build-prod
cd -
npm run start
```
Thanks :)
=> Reflex vdom bench

frameworks/keyed/mahal/package-lock.json, frameworks/keyed/mahal/package.json, frameworks/keyed/mahal/src/app.mahal
=> update mahal version to 1.4.0

frameworks/keyed/react-starbeam/.babelrc, frameworks/keyed/react-starbeam/index.html, frameworks/keyed/react-starbeam/package-lock.json, frameworks/keyed/react-starbeam/package.json, frameworks/keyed/react-starbeam/src/data.js, frameworks/keyed/react-starbeam/src/jumbotron.jsx, frameworks/keyed/react-starbeam/src/main.jsx, frameworks/keyed/react-starbeam/webpack.config.js
Demos React with a universal reactivity implementation, Starbeam. https://github.com/starbeamjs [docs](https://starbeamjs.com/)
Preliminary results with Starbeam 0.5.8:
=> React 18 + Starbeam

frameworks/keyed/react-starbeam/index.html
Starbeam isn't quite ready for production yet, and I want to make that clear in the demo.
There is a bunch of debug tooling still in the build.
=> Add clarification about the state of starbeam

frameworks/keyed/whatsup/package-lock.json, frameworks/keyed/whatsup/package.json, frameworks/keyed/whatsup/src/main.tsx
@krausest hi! 
Will I still have time to get into the results for chrome 104?
In the previous version, I made a small mistake, due to which performance was significantly reduced. This version has fixed it. 
Thank you!
=> Update whatsup to v2.3.6

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json
It's been a few released, so here's an update.
For whatever reason the script that rebuilds the table is failing on me, I get this in the console:
```
ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts
[tsl] ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts(24,106)
TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
Type 'undefined' is not assignable to type 'string'.
ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts
[tsl] ERROR in /Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts-results/src/reducer.ts(27,67)
TS2345: Argument of type '{ name: string | undefined; dir: …
```
=> Updated Voby to v0.37

frameworks/keyed/react-starbeam/index.html, frameworks/keyed/react-starbeam/package-lock.json, frameworks/keyed/react-starbeam/package.json, frameworks/keyed/react-starbeam/src/main.jsx
- Upgrades starbeam deps
- uses more idiomatic React
=> Upgrade starbeam in react starbeam

frameworks/keyed/gyron/package-lock.json, frameworks/keyed/gyron/package.json, frameworks/keyed/gyron/src/main.jsx, frameworks/keyed/gyron/webpack.config.js, frameworks/non-keyed/gyron/package-lock.json, frameworks/non-keyed/gyron/package.json, frameworks/non-keyed/gyron/src/main.jsx, frameworks/non-keyed/gyron/webpack.config.js
@krausest Hi, I have upgraded my version of the framework and this update optimizes the runtime speed
=> perf: upgrade to v0.0.16

frameworks/keyed/mahal/config/webpack/base.config.js, frameworks/keyed/mahal/config/webpack/dev.config.js, frameworks/keyed/mahal/config/webpack/prod.config.js, frameworks/keyed/mahal/package-lock.json, frameworks/keyed/mahal/package.json
=> update mahaljs to 1.4.3

frameworks/keyed/react-diagon/index.html, frameworks/keyed/react-diagon/package-lock.json, frameworks/keyed/react-diagon/package.json, frameworks/keyed/react-diagon/src/main.tsx, frameworks/keyed/react-diagon/tsconfig.json, frameworks/keyed/react-diagon/webpack.config.js
Adding Diagon state management for React.
=> add Diagon to keyed/frameworks

frameworks/non-keyed/legend-state/index.html, frameworks/non-keyed/legend-state/package-lock.json, frameworks/non-keyed/legend-state/package.json, frameworks/non-keyed/legend-state/src/main.jsx, frameworks/non-keyed/legend-state/webpack.config.js
This adds benchmarks for legend-state. See https://legendapp.com/dev/state for more info.
One thing that's unusual about this library: when an array is updated and the length did not change, it short-circuits React and updates the existing elements in place. So although the arrays are very much keyed, the "swap" benchmark says it's not keyed because the list does not re-render and elements are updated in place. So I'm not sure whether you want to consider it keyed overall.
=> Add legend-state benchmark

frameworks/keyed/react-hooks/src/main.jsx
Hi! In this PR, I implemented time slicing for `React` by wrapping dispatch in `startTransition`.
=> React 18 with concurrent features

frameworks/keyed/preact-signals/index.html, frameworks/keyed/preact-signals/package-lock.json, frameworks/keyed/preact-signals/package.json, frameworks/keyed/preact-signals/rollup.config.js, frameworks/keyed/preact-signals/src/main.jsx
Still figuring out if this is the best way of accomplishing this. Tried a few different versions but they have different tradeoffs. I also think I may have stumbled on a memory leak. Wouldn't mind a review.
@developit @marvinhagemeister
Thanks,
=> Preact Signals Implementation

frameworks/keyed/react-tagged-state/package-lock.json, frameworks/keyed/react-tagged-state/package.json, frameworks/keyed/react-tagged-state/src/main.jsx
I improved react integration is react-tagged-state.
Also, I swap to jotai implementation
=> Update react-tagged-state to latest

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json
Update after a few releases. Mainly there was a decent optimization I had missed.
=> Updated Voby to v0.42.1

frameworks/keyed/svelte/package-lock.json, frameworks/keyed/svelte/package.json, frameworks/non-keyed/svelte/package-lock.json, frameworks/non-keyed/svelte/package.json
Major performance increase during SSR: https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3490
=> Upgrade to latest version of Svelte

frameworks/keyed/karyon/package-lock.json, frameworks/keyed/karyon/package.json, frameworks/keyed/karyon/src/main.js
Updating to the latest version of library, as some micro-optimizations were done since the last update. Also, a minor refactoring of implementation which could save a few bytes of memory on create rows.
=> Update karyon to v1.4.3

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json
Lots of litte-ish internal changes, so here's an update.
=> Updated Voby to v0.43

frameworks/keyed/udomsay/index.html, frameworks/keyed/udomsay/package-lock.json, frameworks/keyed/udomsay/package.json, frameworks/keyed/udomsay/rollup.config.js, frameworks/keyed/udomsay/src/main.jsx, frameworks/non-keyed/udomsay/index.html, frameworks/non-keyed/udomsay/package-lock.json, frameworks/non-keyed/udomsay/package.json, frameworks/non-keyed/udomsay/rollup.config.js, frameworks/non-keyed/udomsay/src/main.jsx
While I am still working on some possible performance improvements I am already pretty happy about the current [udomsay](https://github.com/WebReflection/udomsay#readme) result and I'd love to see it as part of the table, where the goal is to compete with other JSX based implementations in terms of memory consumption, code size and, after all, raw performance.
Thank you in advance for considering this addiction.
=> udomsay - a vDOM-less JSX & signals based library

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json
Lots of internal tweaks, if I haven't messed anything up, which I'm not sure about, they might amount to something.
=> Updated Voby to v0.43.6

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json
I found a couple of optimizations, I think they might have a small impact especially in the "append rows" test.
=> Updated Voby to v0.43.8

frameworks/keyed/riot/package-lock.json, frameworks/keyed/riot/package.json, frameworks/non-keyed/riot/package-lock.json, frameworks/non-keyed/riot/package.json
I thought that [`replaceChildren`](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren) was a better alternative to while loops. I was wrong :)
=> Update Riot.js to v7.1

frameworks/keyed/maverick/package-lock.json, frameworks/keyed/maverick/package.json, frameworks/keyed/maverick/src/main.tsx
Sorry to be a pain @krausest, just a quick bump as I've resolved some small issues with scheduling and the select row bench. Numbers should be stable now until I revise everything in a month or two.
Note: Turns out I was also creating thousand/s of effects for no reason -_- lol. Fixed that too.
=> update maverick to 0.22.2

frameworks/keyed/maverick/build.js, frameworks/keyed/maverick/package-lock.json, frameworks/keyed/maverick/package.json, frameworks/keyed/maverick/src/main.tsx
Overall minor improvements across the board + big memory improvements.
=> update maverick to 0.23.1

webdriver-ts-results/src/App.tsx
=> Fix a typo

frameworks/keyed/whatsup/package.json
Hi @krausest
Please take a look at this when you have time.
=> Update whatsup to v2.5.0

webdriver-ts-results/src/Common.ts
Add missing space (typo) in `webdriver-ts-results` categories :)
=> Add missing space (typo)

frameworks/keyed/bobril/.bbrc, frameworks/keyed/bobril/index.html, frameworks/keyed/bobril/package-lock.json, frameworks/keyed/bobril/package.json, frameworks/keyed/bobril/src/app.ts
Should fix performance regression in row swapping.
=> Update to latest Bobril 20.4.1

frameworks/keyed/react-signalis/index.html, frameworks/keyed/react-signalis/package-lock.json, frameworks/keyed/react-signalis/package.json, frameworks/keyed/react-signalis/src/main.jsx, frameworks/keyed/react-signalis/vite.config.js
Hi there!
I wanted to submit a benchmark for my reactivity library [Signalis](https://github.com/cafreeman/signalis). I followed all the directions in the README and everything works great locally, but this is my first time so please let me know if I've missed anything.
Thanks!
=> submit react-signalis benchmark

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json, frameworks/keyed/voby/src/main.tsx
I couldn't run the bench locally because of this error:
```
ERROR  SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 110.0.5481.177 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
at Object.throwDecodedError (/Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/error.js:524:15)
at parseHttpResponse (/Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/http.js:587:13)
at Executor.execute (/Users/fabio/Code/fabiospampinato/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/http.js:515:28)
at process.processTicksAndRejections …
```
=> Updated Voby to v0.45

frameworks/keyed/karyon/app.js, frameworks/keyed/karyon/package-lock.json, frameworks/keyed/karyon/package.json
An update to the latest version of `karyon` module, also a bit of refactoring of the benchmark implementation which may yield a few femtoseconds of performance gain, hopefully.
=> `karyon` update

frameworks/keyed/voby/package-lock.json, frameworks/keyed/voby/package.json, frameworks/non-keyed/voby/index.html, frameworks/non-keyed/voby/package-lock.json, frameworks/non-keyed/voby/package.json, frameworks/non-keyed/voby/src/main.tsx
- I switched to a lazy reactivity system, so mandatory update for that.
- I also added an unkeyed implementation, which performs surprisingly poorly 🤔 I should look more into that.
=> Updated Voby to v0.48

frameworks/non-keyed/slingjs/index.html, frameworks/non-keyed/slingjs/package-lock.json, frameworks/non-keyed/slingjs/package.json, frameworks/non-keyed/slingjs/src/controller.js, frameworks/non-keyed/slingjs/src/main.es6.js
* Update to Sling.js version 18.0.0.
Tested on:
```
npm 9.5.0
node 18.15.0
```
=> Update to Sling.js version 18.0.0

frameworks/keyed/react-tagged-state/package-lock.json, frameworks/keyed/react-tagged-state/package.json, frameworks/keyed/react-tagged-state/src/main.jsx
I reset implementation to react-hooks, I removed any hacks and optimizations to understand difference between pure react and react-tagged-state for basic usage.
I'm expecting performance drop
=> Update react-tagged-state to 1.23.0

frameworks/keyed/whatsup/package.json
Hi @krausest
Please take a look at this when you have time.
=> Update whatsup to v2.6.0

frameworks/keyed/alpine/package-lock.json, frameworks/keyed/alpine/package.json
* Update Alpine.js to version 3.12.0.
Tested on:
```
npm 9.5.0
Node v18.15.0
```
=> Update Alpine.js to version 3.12.0

frameworks/keyed/million/package-lock.json, frameworks/keyed/million/package.json, frameworks/keyed/million/rollup.config.mjs
bumps `million` version from 2.1.2 to 2.3.3
=> chore(Million.js): bump version

frameworks/keyed/svelte/package-lock.json, frameworks/keyed/svelte/package.json, frameworks/non-keyed/svelte/package-lock.json, frameworks/non-keyed/svelte/package.json, frameworks/non-keyed/svelte/rollup.config.js
- Update Svelte keyed and non-keyed to v4.0.0
- Update rollup plugins
- Fix non-keyed rollup config
=> Update Svelte to v4.0.0

frameworks/non-keyed/cample/index.html, frameworks/non-keyed/cample/package-lock.json, frameworks/non-keyed/cample/package.json, frameworks/non-keyed/cample/src/main.js, frameworks/non-keyed/cample/webpack.config.js
Cample.js framework implementation.
=> Add cample

frameworks/keyed/metron/index.html, frameworks/keyed/metron/package-lock.json, frameworks/keyed/metron/package.json, frameworks/keyed/metron/rollup.config.mjs, frameworks/keyed/metron/src/main.jsx, frameworks/keyed/metron/tsconfig.json
I put this under the keyed category because it passes the keyed test and functionally does the same thing and only affects the corresponding dom nodes. Instead of keys it uses fine grained messages on data changes to update the dom rather than a key per each item. You can see the dom manipulation paths for each data change type here: https://github.com/robbiespeed/metron/blob/856e14307827b0dc6c6dcf3a7b63fe4ea7328169/packages/jsx/src/web-dom/render.ts#L424
=> add metron 0.0.2

frameworks/keyed/vue/package-lock.json, frameworks/keyed/vue/package.json, frameworks/non-keyed/vue/package-lock.json, frameworks/non-keyed/vue/package.json
- Update Vue to 3.3.4
- Update webpack deps
=> Update Vue to 3.3

frameworks/keyed/solid/package-lock.json, frameworks/keyed/solid/package.json, frameworks/keyed/solid/rollup.config.js
- Update solid.js to 1.7.8
- Update rollup & babel
=> Update Solid.js to 1.7

zip.js
Perf: same execution time, 30% less memory consumption, 3% less CPU usage.
- Moved the addition of files and directories and checking their presence to separate functions.
- Added JSDoc comments and types.
- Removed a lot of if..else.
- Removed unused imports.
=> refactor: zip.js

server/config/directories.js, server/csp/cspControllers.js, server/csp/cspRouter.js, server/frameworks/frameworksControllers.js, server/frameworks/frameworksRouter.js, server/frameworks/helpers/index.js, server/frameworks/utils/isFrameworkDir.js, server/index.js, server/middlewares/addSiteIsolationForIndex.js, server/package-lock.json, server/package.json
- Update nodemon, express and body-parser.
- Rewrite the server using ES modules instead of commonjs.
- Split the code into modules.
- Refactor: remove if...else hell, change object property reference to dot method, remove copyProps() function from loadFrameworkInfo scope, remove unnecessary async declarations, replace let with const where possible, type some functions using JSDoc.
- Format using prettier.
=> Refactor server

copy.js
- Add JSDoc comments and type annotations to improve code documentation.
- Refactor the `copyFolderRecursive` function.
- Split the code into separate functions for better organization and reusability.
- Replace the custom `copyFileRecursive` function with the more efficient built-in `fs.copyFileSync` method.
- Replace the usage of `indexOf` with `includes` for better clarity and simplicity.
- Update string concatenation to use string templates for improved readability.
- Replace `var` declarations with `let` and `const`.
- Replace the usage of lodash's `each` method with the native `for..of` loop for better performance.
- Replace names of variables and functions with more understandable ones.
- Remove copying of Stem polyfill.
=> refactor: copy.js

rebuild-all.js
- Add or fix JSDoc comments.
- Change the method of deleting files from `execSync`, to `fs.rmSync`. As a result, the execution time of the rebuildFrameworks function decreased by ~10 times (*1) and memory consumption by 50% (*1).
- Change the framework view from the [dir,name] array to the {type, name} object.
- Move the rebuild of the framework into the `rebuildFramework` function.
- Improve performance of getting args.
- Improve cross-platform.
*1 - Measured without `installCmd` and `buildCmd` calls.
=> perf, refactor: improve rebuild-all.js

README.md
Found a small error in the README.
Changes:
- Remove an extra word in the readme file
=> fix: grammar error in readme file

rebuild-build-single.js
- Add JSDoc types.
- Move the rebuild of all frameworks to `rebuildFrameworks` function.
- Move framework rebuild to `rebuildFramework` function.
- Move CLI command execution and logging to `runCommand` function.
And some smaller updates.
=> refactor(rebuild-build-single): improve readability

frameworks/keyed/1more/package-lock.json, frameworks/keyed/1more/package.json, frameworks/keyed/1more/rollup.config.js
Simply update the rollup-* and package-lock.json versions
=> chore: update 1more deps

frameworks/non-keyed/cample/package-lock.json, frameworks/non-keyed/cample/package.json, frameworks/non-keyed/cample/src/main.js
Also, changed main.js for the new version
=> Update cample to v3.0.6

frameworks/non-keyed/bau/main.js, frameworks/non-keyed/bau/package.json
* new api for array
* performance improvement for partial update
=> Bau update

frameworks/keyed/dark/package-lock.json, frameworks/keyed/dark/package.json, frameworks/keyed/dark/src/index.ts, frameworks/keyed/dark/webpack.config.js
Updates Dark to the 0.25.1 version
=> Update Dark to 0.25.1

webdriver-ts-results/package-lock.json, webdriver-ts-results/package.json, webdriver-ts-results/src/components/ResultTable.tsx, webdriver-ts-results/src/components/selection/BenchmarkSelector/BenchmarkSelectorCategory.tsx, webdriver-ts-results/src/components/selection/CopyPasteSelection.tsx, webdriver-ts-results/src/components/selection/FrameworkSelector/FrameworkSelectorCategory.tsx, webdriver-ts-results/src/components/selection/ModeSelector/index.tsx, webdriver-ts-results/src/components/tables/CompareRow.tsx, webdriver-ts-results/src/index.tsx, webdriver-ts-results/src/reducer.ts
This is simply replacing redux with zustand in order to reduce boilerplate code and the size of the bundle.
=> refactor(web-ts-results): replace redux with zustand

frameworks/keyed/dlightjs/package-lock.json, frameworks/keyed/dlightjs/package.json, frameworks/keyed/dlightjs/rollup.config.js, frameworks/keyed/dlightjs/src/main.js, frameworks/non-keyed/dlightjs/package-lock.json, frameworks/non-keyed/dlightjs/package.json, frameworks/non-keyed/dlightjs/rollup.config.js, frameworks/non-keyed/dlightjs/src/main.js
Upgrading [DLight.js](https://github.com/dlight-js/dlight) to 0.10.x
=> feat: upgrade DLight.js to 0.10.x

package-lock.json, package.json
Just updating root dependencies.
=> chore(root): bump deps

frameworks/keyed/svelte/src/Main.svelte
This updates the Svelte 4 implementation so it's a bit clearer to follow and also uses `immutable` mode. There shouldn't be any real differences in performance – however this should be slightly easier to follow and read.
=> Cleanup Svelte 4 implementation

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json, frameworks/keyed/cample/src/main.js
Changed values. Now, select row should be at good speed
=> Update cample to v3.2.0-beta.0

broken-frameworks/keyed/bobril/.bbrc, broken-frameworks/keyed/bobril/index.html, broken-frameworks/keyed/bobril/package-lock.json, broken-frameworks/keyed/bobril/package.json
Could not reproduce #1402 so atleast upgraded everything to latest version and added --verbose to build command hoping it could help investigate problem.
=> Update bobril to latest version

frameworks/keyed/vue-pinia/index.html, frameworks/keyed/vue-pinia/package-lock.json, frameworks/keyed/vue-pinia/package.json, frameworks/keyed/vue-pinia/src/App.vue, frameworks/keyed/vue-pinia/src/data.js, frameworks/keyed/vue-pinia/src/main.js, frameworks/keyed/vue-pinia/src/store.js, frameworks/keyed/vue-pinia/webpack.config.js
Pinia has recently been made the [official vue store](https://vuex.vuejs.org/), and successor to vuex
https://pinia.vuejs.org/
=> Add vue-pinia

frameworks/keyed/art/package-lock.json, frameworks/keyed/art/package.json
1. Implement runtime and time slicing using the web-scheduler component library.
2. Use setImmediate instead of requestAnimationFrame. Performing extensive DOM operations in the requestAnimationFrame phase is not a good choice.
=> update art to v1.1.0

frameworks/keyed/owl/index.html, frameworks/keyed/owl/package-lock.json, frameworks/keyed/owl/package.json, frameworks/keyed/owl/src/Root.js, frameworks/keyed/owl/src/data.js, frameworks/keyed/owl/src/main.js, frameworks/keyed/owl/webpack.config.js
OWL is a 25kb framework with class based components (not functions) with hooks, reactive state and concurrent mode. It was build as a part of Odoo, but can be used independently. 919 github stars.  https://github.com/odoo/owl
This test is almost complete copy of Vue test, but with Owl's syntax.
=> adds OWL framework

frameworks/keyed/strve/src/main.jsx
Strve.js optimizes logic code. Thank you to the author for his contribution！
=> Strve optimizes logic code

README.md, frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json, frameworks/keyed/cample/src/main.js
I think this should definitely fix select row!
=> Update cample to v3.2.0-beta.2

frameworks/keyed/vue/package-lock.json, frameworks/keyed/vue/package.json, frameworks/non-keyed/vue/package-lock.json, frameworks/non-keyed/vue/package.json
- Update Vue to 3.3.6
- Update webpack deps
=> Update Vue to 3.3.6

webdriver-ts-results/src/App.css
Fixed disappearing borders on the left and right of the first columns of tables when scrolling.
=> fix(web): disappearing border on the left side of tables when scrolling

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json
Now, I hope, select row should become normal)
=> Update cample to v3.2.0-beta.4

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json
I'm apologize for the inconvenience to do pull request again so early. I hope the framework will have time to get into release 119. The next versions will no longer go like this every week, so as not to distract you every time. It's just, well, it really turned out cool according to the code :)
=> Update cample to v3.2.0-beta.5

frameworks/keyed/angular-cf-nozone/package-lock.json, frameworks/keyed/angular-cf-nozone/package.json, frameworks/keyed/angular-cf-nozone/src/index.html, frameworks/keyed/angular-cf-signals/package-lock.json, frameworks/keyed/angular-cf-signals/package.json, frameworks/keyed/angular-cf-signals/src/index.html, frameworks/keyed/angular-cf/package-lock.json, frameworks/keyed/angular-cf/package.json, frameworks/keyed/angular-cf/src/index.html, frameworks/keyed/angular-ngfor/package-lock.json, frameworks/keyed/angular-ngfor/package.json, frameworks/keyed/angular-ngfor/src/index.html
Should be a trivial bump, just to get on stable.
=> Bump Angular to stable 17

frameworks/keyed/svelte/package-lock.json, frameworks/keyed/svelte/package.json, frameworks/keyed/svelte/rollup.config.js, frameworks/keyed/svelte/src/Main.svelte, frameworks/keyed/svelte/src/main.js
This PR updates Svelte to the recent alpha of Svelte 5. It also updates the implementation to make use of the new features available in Svelte 5.
=> Upgrade Svelte to v5 alpha

frameworks/non-keyed/sprae/index.html, frameworks/non-keyed/sprae/package-lock.json, frameworks/non-keyed/sprae/package.json, frameworks/non-keyed/sprae/src/main.js, frameworks/non-keyed/sprae/src/sprae.js
It adds basic test for [sprae](https://github.com/dy/sprae).
Within analogs: alpine, petite-vue it shows locally best results.
@krausest @trueadm
=> Sprae framework

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json
Corrected the code a little. I think select row will be a little faster :)
=> Update cample to v3.2.0-beta.6

frameworks/keyed/frei-hooks/package-lock.json, frameworks/keyed/frei-hooks/package.json, frameworks/non-keyed/frei-hooks/package-lock.json, frameworks/non-keyed/frei-hooks/package.json
screenshot Can include：？ @krausest 
「Startup metrics (lighthouse with mobile simulation)」
「Memory allocation in MBs ± 95% confidence interval 」
=> frei update v1.0.18 { diff logical small-scale optimization }

webdriver-ts-results/package-lock.json, webdriver-ts-results/package.json
https://vitejs.dev/blog/announcing-vite5
=> Use vite 5 for results

frameworks/non-keyed/quel/src/myappMain.js
This PR update quel benchmark, optimize "select row".
=> update quel benchmark, optimize "select row"

frameworks/keyed/qwik/package-lock.json, frameworks/keyed/qwik/package.json
[Release notes](https://github.com/BuilderIO/qwik/releases/tag/v1.3.0)
=> Update qwik to 1.3

frameworks/keyed/strve-reactivity/.gitignore, frameworks/keyed/strve-reactivity/index.html, frameworks/keyed/strve-reactivity/package-lock.json, frameworks/keyed/strve-reactivity/package.json, frameworks/keyed/strve-reactivity/src/data.js, frameworks/keyed/strve-reactivity/src/main.jsx, frameworks/keyed/strve-reactivity/webpack.config.js
=> Add keyed/strve-reactivity

frameworks/keyed/rendrjs-atoms/package-lock.json, frameworks/keyed/rendrjs-atoms/package.json, frameworks/keyed/rendrjs-atoms/src/Jumbotron.js, frameworks/keyed/rendrjs/package-lock.json, frameworks/keyed/rendrjs/package.json, frameworks/keyed/rendrjs/src/main.js
=> Update rendrjs version

frameworks/non-keyed/sprae/package-lock.json, frameworks/non-keyed/sprae/package.json
This adds few enhancements to objects, doesn't really improve performance, but to be in sync.
Also @krausest I wonder was it really necessary to remove petite-vue - it is unique in class framework, one good viable alternative to alpine - it doesn't seem to be needed to be updated frequently, since it's state of art.
It would be also help to compare alpine, petite-vue, sprae as 3 similar frameworks in class. Wdyt adding it back?
=> Sprae 8.1.2

webdriver-ts/src/benchmarksPuppeteer.ts
Changing `config.WARMUP_COUNT` will break the benchmarks. This fixes it.
=> Wamup count from config used in assertions

frameworks/keyed/mikado-proxy/package-lock.json, frameworks/keyed/mikado-proxy/package.json, frameworks/keyed/mikado-proxy/src/data.js, frameworks/keyed/mikado/package-lock.json, frameworks/keyed/mikado/package.json, frameworks/non-keyed/mikado/package-lock.json, frameworks/non-keyed/mikado/package.json
Includes an improvement of default DOM attributes state and unused attributes
=> update mikado v0.8.222

frameworks/keyed/strve/package-lock.json, frameworks/keyed/strve/package.json, frameworks/keyed/strve/src/main.jsx
=> Update Strve v6.6.6 !

frameworks/keyed/preact-classes/package-lock.json, frameworks/keyed/preact-classes/package.json, frameworks/keyed/preact-classes/webpack.config.js, frameworks/keyed/preact-hooks/package-lock.json, frameworks/keyed/preact-hooks/package.json, frameworks/keyed/preact-signals/package-lock.json, frameworks/keyed/preact-signals/package.json
updates preact-signals/-hooks/-classes and their the dev deps
=> update preact -> 10.19.3

frameworks/keyed/gxt/package-lock.json, frameworks/keyed/gxt/package.json, frameworks/keyed/gxt/src/Button.gts, frameworks/keyed/gxt/src/RemoveIcon.gts, frameworks/keyed/gxt/src/Row.gts, frameworks/keyed/gxt/tsconfig.json, frameworks/keyed/gxt/vite.config.mts
Prev: https://github.com/krausest/js-framework-benchmark/pull/1561
=> Update GXT to 0.0.37

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json
I think this will be 1.09 (I also committed a version there that improved the code a little)
=> Update cample to v3.2.0-alpha.7

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json
Now, it should definitely be 1.09!
=> Update cample to v3.2.0-alpha.11

frameworks/keyed/strve/package-lock.json, frameworks/keyed/strve/package.json
=> Update Strve v6.7.0

frameworks/keyed/riot/package-lock.json, frameworks/keyed/riot/package.json, frameworks/non-keyed/riot/package-lock.json, frameworks/non-keyed/riot/package.json
=> updated: Riot.js version

frameworks/keyed/solid-store/package-lock.json, frameworks/keyed/solid-store/package.json, frameworks/keyed/solid-store/rollup.config.js, frameworks/keyed/solid-store/src/main.jsx, frameworks/keyed/solid/package-lock.json, frameworks/keyed/solid/package.json
make the setup of solid and solid-store identical and updated. This updates the solid-store as well. shouldn't cause significant change
=> clean up solid / solid-store devdeps

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json, frameworks/keyed/cample/src/main.js
If this doesn’t help, I don’t understand yet, but it seems like it should help
=> Update cample to 3.2.0-alpha.29

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json, frameworks/keyed/cample/src/main.js
I'll try to do that. I think it will be faster
=> Update cample to 3.2.0-alpha.33

frameworks/keyed/destam-dom/index.html, frameworks/keyed/destam-dom/package-lock.json, frameworks/keyed/destam-dom/package.json, frameworks/keyed/destam-dom/rollup.config.js, frameworks/keyed/destam-dom/src/main.jsx
https://github.com/Nefsen402/destam-dom
This was mostly copy pasted from the solidjs benchmark
=> Introduce destam-dom benchmark

frameworks/keyed/pota/package.json, frameworks/keyed/pota/src/main.jsx
Hey, 
I have finally dealt with the "clear rows", also greatly improved other areas. If lucky, it may jump a few dozen places, hopefully forward xD.  I see you have added a package-lock, I haven't touched it, I'm not really sure if it needs an update. 
Thanks!
=> Update pota 

frameworks/keyed/lwc/package-lock.json, frameworks/keyed/lwc/package.json
We have some optimizations in the latest release.
Thank you for continuing to maintain this benchmark! 🙇
=> chore: update lwc

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json, frameworks/keyed/cample/src/main.js
Fixed select row. It will be better.
=> Update cample to 3.2.0-alpha.45

frameworks/keyed/cample/package-lock.json, frameworks/keyed/cample/package.json, frameworks/keyed/cample/src/main.js, frameworks/keyed/vanillajs-2/index.html, frameworks/keyed/vanillajs-2/package-lock.json, frameworks/keyed/vanillajs-2/package.json, frameworks/keyed/vanillajs-2/src/Main.js
#1661 I made the code here just as an example, maybe it will help someone (You don’t need to upload it. I’ll delete it later after vanillajs new)
=> #1661 Test vanillajs-2

frameworks/keyed/svelte-classic/package-lock.json, frameworks/keyed/svelte-classic/package.json, frameworks/keyed/svelte/package-lock.json, frameworks/keyed/svelte/package.json, frameworks/keyed/vue-jsx/package-lock.json, frameworks/keyed/vue-jsx/package.json, frameworks/keyed/vue-pinia/package-lock.json, frameworks/keyed/vue-pinia/package.json, frameworks/keyed/vue-vapor/package-lock.json, frameworks/keyed/vue-vapor/package.json, frameworks/keyed/vue-vapor/src/main.js, frameworks/keyed/vue/package-lock.json, frameworks/keyed/vue/package.json, frameworks/non-keyed/svelte-classic/package-lock.json, frameworks/non-keyed/svelte-classic/package.json, frameworks/non-keyed/vue-vapor/package-lock.json, frameworks/non-keyed/vue-vapor/package.json, frameworks/non-keyed/vue-vapor/src/main.js, frameworks/non-keyed/vue/package-lock.json, frameworks/non-keyed/vue/package.json
Updates Vue, Vue-Vapor and Svelte to the latest version. The latest versions of these packages contain performance improvements and bug fixes.
=> Update Vue, Vue-Vapor and Svelte

frameworks/keyed/deleight/index.html, frameworks/keyed/deleight/package-lock.json, frameworks/keyed/deleight/package.json, frameworks/keyed/deleight/rollup.config.mjs, frameworks/keyed/deleight/src/Main.js, frameworks/keyed/vanillajs-3/index.html, frameworks/keyed/vanillajs-3/package-lock.json, frameworks/keyed/vanillajs-3/package.json, frameworks/keyed/vanillajs-3/src/Main.js, frameworks/keyed/vanillajs-lite/index.html, frameworks/keyed/vanillajs-lite/package-lock.json, frameworks/keyed/vanillajs-lite/package.json, frameworks/keyed/vanillajs-lite/src/Main.js, frameworks/non-keyed/deleight/index.html, frameworks/non-keyed/deleight/package-lock.json, frameworks/non-keyed/deleight/package.json, frameworks/non-keyed/deleight/rollup.config.mjs, frameworks/non-keyed/deleight/src/Main.js, package-lock.json, webdriver-ts/src/common.ts, webdriver-ts/src/forkedBenchmarkRunnerPuppeteer.ts, webdriver-ts/src/puppeteerAccess.ts
I have created a powerful new web framework comprising 7 independent libraries and directly benefited from using these benchmarks to test and improve my abstractions. The performance is very good. And thanks for doing these benchmarks.
=> Added Eventiveness Web framework

frameworks/keyed/lwc/package-lock.json, frameworks/keyed/lwc/package.json
We have another small optimization in this version. Thanks very much in advance! 🙇
=> chore: bump lwc to v6.6.1

frameworks/keyed/reflex-js-atomic/esbuild.config.js, frameworks/keyed/reflex-js-atomic/index.html, frameworks/keyed/reflex-js-atomic/package-lock.json, frameworks/keyed/reflex-js-atomic/package.json, frameworks/keyed/reflex-js-atomic/src/main.tsx, frameworks/keyed/reflex-js-atomic/tsconfig.json, frameworks/keyed/reflex-js/package-lock.json
This bench add some fine-grained updates to the diff. I created a new bench to check if it worth it.
The main has been updated.
=> Updated reflex benchs

frameworks/keyed/vanillajs-3/index.html, frameworks/keyed/vanillajs-3/package-lock.json, frameworks/keyed/vanillajs-3/package.json, frameworks/keyed/vanillajs-3/src/Main.js
I still attempted an implementation that was faster for creating 1K rows. I could not go faster here. However, I found consistent gains in other areas.
=> VanillaJS-3 implementation

frameworks/keyed/vanillajs-3/index.html, frameworks/keyed/vanillajs-3/src/Main.js, frameworks/non-keyed/vanillajs-3/index.html, frameworks/non-keyed/vanillajs-3/package-lock.json, frameworks/non-keyed/vanillajs-3/package.json, frameworks/non-keyed/vanillajs-3/src/Main.js
- added non-keyed implementation for Vanillajs-3
- small code enhancements
- semantic bug fix (in remove) for the keyed implementation.
=> Non-keyed implementation

frameworks/keyed/vanillajs-lite/src/Main.js
Updating due to regression observed in #1676, also for newer optimizations.
=> `vanillajs-lite` update

frameworks/keyed/destam-dom/package-lock.json, frameworks/keyed/destam-dom/package.json, frameworks/keyed/destam-dom/src/main.jsx
+ some optimizations and simplifications
This removes the last low hanging fruit in terms of perf improvements. I don't think I can get much better than this.
=> destam-dom: Update library

frameworks/keyed/vue-jsx/package-lock.json, frameworks/keyed/vue-jsx/package.json, frameworks/keyed/vue-pinia/package-lock.json, frameworks/keyed/vue-pinia/package.json, frameworks/keyed/vue-vapor/package-lock.json, frameworks/keyed/vue-vapor/package.json, frameworks/keyed/vue-vapor/src/App.vue, frameworks/keyed/vue-vapor/vite.config.js, frameworks/keyed/vue/package-lock.json, frameworks/keyed/vue/package.json, frameworks/non-keyed/vue-vapor/package-lock.json, frameworks/non-keyed/vue-vapor/package.json, frameworks/non-keyed/vue-vapor/src/App.vue, frameworks/non-keyed/vue-vapor/vite.config.js, frameworks/non-keyed/vue/package-lock.json, frameworks/non-keyed/vue/package.json
Updates Vue, Vue-Vapor to the latest version
=> Update Vue, Vue-Vapor

frameworks/keyed/svelte-classic/package-lock.json, frameworks/keyed/svelte-classic/package.json, frameworks/keyed/svelte/package-lock.json, frameworks/keyed/svelte/package.json, frameworks/non-keyed/svelte-classic/package-lock.json, frameworks/non-keyed/svelte-classic/package.json
Updates to the latest version of Svelte.
=> Upgrade Svelte

frameworks/keyed/deleight/index.html, frameworks/keyed/deleight/package-lock.json, frameworks/keyed/deleight/package.json, frameworks/keyed/deleight/src/Main.js, frameworks/keyed/vanillajs-3/index.html, frameworks/keyed/vanillajs-3/src/Main.js, frameworks/non-keyed/deleight/package-lock.json, frameworks/non-keyed/deleight/package.json
I found some ideas to improve both implementations. They show good improvements locally.
=> Updated Vanillajs-3 and Deleight implementations

frameworks/keyed/vue-vapor/src/App.vue, frameworks/keyed/vue-vapor/src/data.js, frameworks/non-keyed/vue-vapor/src/App.vue, frameworks/non-keyed/vue-vapor/src/data.js
related https://github.com/vuejs/core-vapor/pull/268
Improve the test code based on the architectural features of Vue Vapor
This can more accurately reflect the best situation. Then we will try to fix some of the slower parts.
This is the result of my computer:
=> perf: improve vue-vapor test code

frameworks/keyed/angular-cf-nozone/package.json, frameworks/keyed/angular-cf-signals/package.json, frameworks/keyed/angular-cf/package.json, frameworks/keyed/angular-ngfor/package.json
Angular has new website on https://angular.dev/.
=> Changed Angular docs to angular.dev

frameworks/keyed/hono/.gitignore, frameworks/keyed/hono/index.html, frameworks/keyed/hono/package-lock.json, frameworks/keyed/hono/package.json, frameworks/keyed/hono/src/index.tsx, frameworks/keyed/hono/tsconfig.json, frameworks/keyed/hono/vite.config.js
This adds Hono client-side benchmarks. The code was adapted from the React-hooks implementation
=> Add Hono client-side benchmarks

frameworks/keyed/lwc/package-lock.json, frameworks/keyed/lwc/package.json
This is just a regularly-scheduled dependency update.
Thank you as always for continuing to maintain this repo! 🙇
=> chore: update lwc to v7.2.6

frameworks/non-keyed/mutraction/package-lock.json, frameworks/non-keyed/mutraction/package.json
No functionality or logic changes
=> Update version for mutraction-dom to 0.27.0

frameworks/keyed/mikado-proxy/package-lock.json, frameworks/keyed/mikado-proxy/package.json, frameworks/keyed/mikado/package-lock.json, frameworks/keyed/mikado/package.json, frameworks/non-keyed/mikado/package-lock.json, frameworks/non-keyed/mikado/package.json
Bumped mikado to `0.8.400` 🐈‍⬛
=> Bump mikado to `0.8.400`

frameworks/keyed/solid-store/package-lock.json, frameworks/keyed/solid-store/package.json, frameworks/keyed/solid/package-lock.json, frameworks/keyed/solid/package.json
This is only minor releases, no code changes needed.
=> update solid and solid-store

frameworks/keyed/strve-rv/src/main.jsx
#801 
Make corresponding adjustments for this point.
=> Adjust the main logic code

frameworks/keyed/michijs/michi.config.ts, frameworks/keyed/michijs/package-lock.json, frameworks/keyed/michijs/package.json, frameworks/keyed/michijs/public/index.html, frameworks/keyed/michijs/src/index.tsx
=> Bump michijs to 2.1.4

frameworks/keyed/vanillajs-signals/michi.config.ts, frameworks/keyed/vanillajs-signals/package-lock.json, frameworks/keyed/vanillajs-signals/package.json, frameworks/keyed/vanillajs-signals/public/index.html, frameworks/keyed/vanillajs-signals/src/index.js, frameworks/keyed/vanillajs-signals/tsconfig.json
I wanted to share a VanillaJS implementation using the TC39 Signals polyfill.
=> Added vanilla implementation with tc39 signals

frameworks/keyed/deleight/package.json, frameworks/non-keyed/deleight/index.html, frameworks/non-keyed/deleight/package-lock.json, frameworks/non-keyed/deleight/package.json, frameworks/non-keyed/deleight/rollup.config.mjs, frameworks/non-keyed/deleight/src/Main.js
I have made the following changes to this fork:
1. Updated package.json of keyed deleight implementation to use the correct repo location.
2. Re-implemented the non-keyed implementation to use the latest version of deleight (v5.5.10).
=> Updated package.json to correct the repo location

frameworks/keyed/rvjs/index.html, frameworks/keyed/rvjs/package-lock.json, frameworks/keyed/rvjs/package.json, frameworks/keyed/rvjs/src/App.jsx
I changed some parts of how @rvjs/core works and made the performance better.
Thanks!
=> Update @rvjs/core version

frameworks/keyed/mettle/.gitignore, frameworks/keyed/mettle/index.html, frameworks/keyed/mettle/package-lock.json, frameworks/keyed/mettle/package.json, frameworks/keyed/mettle/src/data.js, frameworks/keyed/mettle/src/main.jsx, frameworks/keyed/mettle/webpack.config.js
A approachable, fast, flexible and lightweight JavaScript library.
Developing web applications with the mindset of writing native JS！
Document：[https://maomincoding.github.io/mettle-doc/](https://maomincoding.github.io/mettle-doc/)
=> Add keyed/mettle

frameworks/keyed/vue-vapor/package-lock.json, frameworks/keyed/vue-vapor/package.json, frameworks/keyed/vue-vapor/src/App.vue, frameworks/keyed/vue-vapor/src/main.js, frameworks/non-keyed/vue-vapor/package-lock.json, frameworks/non-keyed/vue-vapor/package.json, frameworks/non-keyed/vue-vapor/src/App.vue, frameworks/non-keyed/vue-vapor/src/main.js
The latest vue-vapor version has been removed createSelector and v-memo directive.
=> fix(vue-vapor): update deps

frameworks/non-keyed/sprae/package-lock.json, frameworks/non-keyed/sprae/package.json
It's expected to be slightly smaller & faster.
=> Update sprae to v11.1.1

frameworks/non-keyed/deku/.gitignore, frameworks/non-keyed/deku/index.html, frameworks/non-keyed/deku/package-lock.json, frameworks/non-keyed/deku/package.json, frameworks/non-keyed/deku/spago.lock, frameworks/non-keyed/deku/spago.yaml, frameworks/non-keyed/deku/src/Main.js, frameworks/non-keyed/deku/src/Main.purs
@mikesol Could You help improve performance? Thanks!
Performance is bad bc of         `[ rowsPoll <#~> \rows -> D.tbody_ $ map renderRow rows`
I basically recreate table
and this is actually my first try of deku, and I wonder, should I do custom actions on every `create, ...etc`, or deku has some magic function that can do this for me
_____
very interesting problem: one source of truth, but changes can be inside and outside, looks like problem for vdom, but we dont have it
interesting how You will solve it, will You add vdom to deku?)
____
store signal with data? https://github.com/krausest/js-framework-benchmark/blob/9d6a759dd959a2a377b51f1a95adfdcfc59fa89f/frameworks/keyed/solid/src/main.jsx#L18
but how to do? https://github.com/krausest/js-framework-benchmark/blob/9d6a759dd959a2a377b51f …
=> feat: deku -> add

frameworks/keyed/doohtml-lite/src/main.js
Changed the partial update method
=> doohtml-lite-v0.98.2-june-6-2025

frameworks/keyed/endr/package-lock.json, frameworks/keyed/endr/package.json
This version removes some needless object creation which slightly improves perf/memory usage.
=> endr@0.1.28

webdriver-ts-results/src/components/SelectionToolbar/FrameworkSelector/FrameworkSelectorCategory.tsx, webdriver-ts-results/src/components/SelectionToolbar/SelectorContentContainer/SelectionContentContainer.tsx, webdriver-ts-results/src/store.ts
Added an "Unflagged" button to the "Which frameworks?" modal, alongside "All" and "None". It filters out frameworks with issues/notes, showing only unflagged ones.
=> Allow "unflagged" selection when clicking "Which frameworks?"

frameworks/keyed/endr/package-lock.json, frameworks/keyed/endr/package.json
Bugfixes, not expecting much perf impact
=> endr@0.2.1
