krausest/js-framework-benchmark

angular-v2.0.0-rc4/src/app.ts

I noticed AngularJS 1.x was using `track by` and not the benchmark in Angular 2.
Maybe that'll change slightly the results (it used to have a big impact in ng1, not sure it has the same in ng2).

Add track by to Angular 2

---

inferno-v0.7.13/src/controller.jsx

Other implementations[1] doesn't have `className="x"`, probably a typo
[1] https://github.com/krausest/js-framework-benchmark/blob/8daa626de88b9a6fa49acfd10060e5f7a44cdf22/react-v15.2.0/src/Main.jsx#L91

Fix row className in Inferno

---

domvm-v2.0.0-beta/index.html
domvm-v2.0.0-beta/package.json
domvm-v2.0.0-beta/src/main.js
domvm-v2.0.0-beta/src/store.js

@krausest 
Since you test in Chrome, there's no need to transpile this impl down to ES5.
A simple `npm install` will also pull down `domvm`'s pre-built & minified ES5/umd bundles (in `/dist`), which are used directly by `index.html`. Rather than publishing to npm, i've set the `package.json` dependency to point directly to the git repo & commit. This should make updates easier with less collateral noise.
The perf should be improved over https://github.com/krausest/js-framework-benchmark/pull/70
Thanks!

add domvm-v2.0.0-beta

---

svelte-v1.0.1/index.html
svelte-v1.0.1/package.json
svelte-v1.0.1/rollup.config.js
svelte-v1.0.1/src/DataStore.js
svelte-v1.0.1/src/Main.html
svelte-v1.0.1/src/main.es6.js

Hi – this PR adds version 1.0.1 of [Svelte](https://svelte.technology), which *should* be one of the fastest frameworks here according to my tests locally (though I confess I couldn't get them all to run).
There isn't yet a Webpack loader for Svelte components, so it's using Rollup instead – hope you don't mind me deviating from convention slightly.
Let me know if there's anything else I'd need to do before you could add this. Thanks!

add Svelte example

---

react-v15.4.0/package.json

reduce the node_modules size from 436M to 61M

delete the repetitive babel-core and babel-loader

---

ractive-edge/package.json
ractive-edge/src/main.es6.js

Ractive edge releases are now published to npm with the `edge` tag. This updates the package manifest accordingly. Are fresh modules installed for every benchmark run?
This also swaps from per-row events to delegated events at the table level, which removes the tiny extra browser overhead for calling `addEventListener` and `removeEventListener` 1000 to 10000 times.

update to new ractive edge and use delegated events

---

domvm-v2.0.3-keyed/package.json
domvm-v2.0.3-keyed/src/main.es6.js

this restructures the keyed impl a bit to use subviews w/sCU instead of a monolithic template with `FIXED_BODY` vnode flags. this adds a bit of overhead to the initial creates, but speeds up everything else by reducing the number of vnodes that must be recreated/diffed for each action.

convert domvm-keyed impl to use subviews w/sCU

---

domvm-v2.0.3-non-keyed/package.json

@krausest would be cool if the whole table was regenerated with a "reboot" [1] and Chrome 57.
It may be worth adding a warmup cycle at the beginning of the bench to ensure the laptop's CPU is thermally throttled equally for all libs rather than giving those starting with "a" an advantage. I've also found 32-bit versions of Chrome to perform faster, allocate a lot less mem and be more stable on my machine.
[1] https://github.com/krausest/js-framework-benchmark/pull/145#issuecomment-287638169

bump domvm version for non-keyed impl

---

surplus-v0.4.0/package.json
surplus-v0.4.0/src/controller.ts
surplus-v0.4.0/src/store.ts
surplus-v0.4.0/src/view.tsx
surplus-v0.4.0/webpack.config.js

A couple tweaks to the surplus version
1) bump dependencies to latest versions.  This was mostly to bring in a bugfix in s-array, but I bumped the others while I was there.
2) a few performance tweaks to the keyed implementation:
- when replacing rows, do a clear first, to take advantage of fast path for removing nodes
- use a single computation to set selected row, avoiding creating N computations for N rows (better matches cardinality of state)
With these changes, here are the timings I get for the top four keyed and unkeyed versions.  Curious to see how it comes out for you on your machine this go around.
Thanks!

surplus: bump dep versions; optimize keyed impl some

---

pico-dom-v0.18.0/index.html
pico-dom-v0.18.0/package.json
pico-dom-v0.18.0/src/main.js
pico-dom-v0.18.0/src/menu.js
pico-dom-v0.18.0/src/store.js
pico-dom-v0.18.0/src/table.js
pico-dom-v0.18.0/src/time.js
webdriver-ts/src/common.ts

Here is a fast minimal lib (2.3 kb gzip) with low memory footprint to facilitate the creation of components and lists of components. On my machine, the memory use and overall slowdown is close to svelte. The overall minimized code is also quite close to the compiled svelte code.
More a library than a framework so I will let you decide if it is relevant here:
* all hyperscript functions (definitely not as sexy as other entries)
* no intermediate structure, all direct dom operations
* top-down updates (updating a node cascades down the whole tree)
This is the *keyed* version, the *non-keyed* can be obtained by deleting the [key here](https://github.com/hville/js-framework-benchmark/blob/master/pico-dom-v0.18.0/src/table.js#L32). I can add the other version if there is any interest.
Thanks …

submit pico-dom-v0.18.0 keyed

---

surplus-v0.4.0/package.json
surplus-v0.4.0/src/controller.ts
surplus-v0.4.0/src/store.ts
surplus-v0.4.0/src/view.tsx

A few perf tweaks to Surplus-v0.4.0
- faster clear via rAF
- index rows by id to provide for O(1) select behavior
- bump S-array version, as new version has a fast path to/from empty arrays

surplus: faster clear via rAF, O(1) select row, update to latest S-array

---

svelte-v1.20.2-keyed/index.html
svelte-v1.20.2-keyed/package.json
svelte-v1.20.2-keyed/rollup.config.js
svelte-v1.20.2-keyed/src/DataStore.js
svelte-v1.20.2-keyed/src/Main.html
svelte-v1.20.2-keyed/src/main.es6.js
svelte-v1.20.2-non-keyed/index.html
svelte-v1.20.2-non-keyed/package.json
svelte-v1.20.2-non-keyed/rollup.config.js
svelte-v1.20.2-non-keyed/src/DataStore.js
svelte-v1.20.2-non-keyed/src/Main.html
svelte-v1.20.2-non-keyed/src/main.es6.js

We have a completely new approach to keyed updates now, so it's a good time to update the Svelte implementation. Thanks!

add Svelte 1.20.2, keyed and non-keyed

---

react-v15.5.4-easy-state-v1.0.3/.babelrc
react-v15.5.4-easy-state-v1.0.3/index.html
react-v15.5.4-easy-state-v1.0.3/package.json
react-v15.5.4-easy-state-v1.0.3/rollup.config.dev.js
react-v15.5.4-easy-state-v1.0.3/rollup.config.prod.js
react-v15.5.4-easy-state-v1.0.3/src/Main.jsx
react-v15.5.4-easy-state-v1.0.3/src/Row.jsx
react-v15.5.4-easy-state-v1.0.3/src/logPerf.js
react-v15.5.4-easy-state-v1.0.3/src/randomSentence.js
webdriver-ts/src/common.ts

Add [React Easy State](https://github.com/solkimicreb/react-easy-state)
Easy State is a small package that aims to improve React's own state management instead of delegating it to external libraries - like Redux or MobX. To achieve this, it does two things:
- It replaces React's state and `setState` with plain native JavaScript.
- It autobinds component methods.
On my machine the benchmark scores at around Redux (slightly better). I think that the rollup build is responsible for the faster startup time. I would gladly refactor the other React examples to use ES6 syntax and rollup if the other authors agree (:

add react-easy-state

---

elm-v0.18.0/src/Main.elm

This change adds the equivalent of React's `shouldComponentUpdate` for the Elm implementation.
**First**, I noticed that this optimization was permitted in the following React implementations:
- [react-v15.5.4-keyed](https://github.com/krausest/js-framework-benchmark/blob/master/react-v15.5.4-keyed/src/Row.jsx#L15-L17)
- [react-v15.5.4-redux-v3.6.0](https://github.com/krausest/js-framework-benchmark/blob/master/react-v15.5.4-redux-v3.6.0/src/controller.jsx#L60-L62)
- [react-lite-v0.15.30](https://github.com/krausest/js-framework-benchmark/blob/master/react-lite-v0.15.30/src/Row.jsx#L15-L17)
There are probably others that use similar techniques, but I am not familiar with all of these projects.
**Second**, this technique is very commonly used in Elm applications. The overall technique is …

Add common optimization to elm-v0.18.0

---

elm-v0.18.0/elm-package.json
elm-v0.18.0/src/Main.elm

This change simplifies the `update` logic for selecting items.
In the previous implementation, the `Select` logic included:
1. A `List.map` that deselected all rows.
2. A conversion from `List` to `Array`
3. An update of that `Array`
4. A conversion back from `Array` to `List`
This is quite a bizarre choice because everything *can* be done in that initial `List.map`. This PR changes the code slightly to skip steps 2, 3, and 4.
The benefits of this change include:
- The `elm-community/array-extra` dependency can be removed.
- Less garbage will be produced by skipping these `Array` conversions.
- Less computation is necessary to select an item.
- The resulting code is simpler.
This should improve speed and allocation, but I expect the improvement to be rather small.
Again, thank you for …

Improve row selection in Elm 0.18 implementation

---

elm-v0.18.0/src/Main.elm

This is a small simplification that follows up on 794f3ebd2835dcb742212aea0024925099b7b15d and takes better advantage of that optimization. It yields a modest speedup in the "remove" benchmark.

Forgo positional indexing in Elm

---

surplus-v0.4.0-keyed/src/view.tsx
surplus-v0.4.0-non-keyed/src/view.tsx

@localvoid noticed (#213) that I mistakenly didn't include the aria-hidden="true" attributes in the surplus implementation.  He's right, they should be there, so this adds them.  It does it in a somewhat artless way.  Once I finish my rewrite of the surplus compiler I'll repost a cleaner fix.

add missing aria-hidden="true" attributes to surplus

---

simulacra-v2.1.1-non-keyed/src/main.js

I had previously implemented the remove benchmark using a positional index in the DOM, which was evidently flaky and unreliable. This fixes that by using a CSS selector.
Closes https://github.com/krausest/js-framework-benchmark/issues/216

Fix brittle benchmark implementation in Simulacra.js

---

aurelia-v1.1.2-non-keyed/src/app.html

An optimization is added to the Aurelia JS implementation (one-time binding behavior) for the ID item rendering.

item id is bound one-time in Aurelia

---

reflex-dom-v0.4-keyed/package.json

Installing reflex-dom from `package.json` currently fails - guess I messed up when commiting https://github.com/krausest/js-framework-benchmark/commit/34ce2b0a8d5ccd46580cdbaf3a83a5859406dc43.
Should I add `npm run install-force` & `npm run build-prod-force` to CI ?

Fix filename in reflex-dom's package.json

---

webdriver-ts/src/benchmarkRunner.ts

Blocked by https://github.com/krausest/js-framework-benchmark/issues/232.

Allow running benchmarks in headless mode

---

webdriver-ts/src/benchmarkRunner.ts

Recommended in https://developers.google.com/web/updates/2017/04/headless-chrome
Appears to be required when running under nixos

Disable GPU when running in headless mode for now

---

webdriver-ts/src/benchmarkRunner.ts

We shouldn't need to test for presence of `args.chromeDriver` here since `undefined` is a [valid input](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_ServiceBuilder.html).

Allow supplying custom path to chromedriver executable

---

halogen-v2.1.0-non-keyed/src/Main.purs
pux-v11.0.0-non-keyed/src/Main.purs
thermite-v4.0.0-non-keyed/src/Main.purs

Hi @krausest,
This is a small fix. I had misunderstood the implementation and preserved row IDs after being swapped; this change no longer does that.
This fixes:
https://github.com/krausest/js-framework-benchmark/issues/294
I did not uncomment the `common.ts` file so the frameworks are still disabled in this PR.

Fix issue 294 - Update to "swap rows" implementation

---

surplus-v0.5.0-non-keyed/package.json
surplus-v0.5.0-non-keyed/src/view.tsx

Hi Stefan --
This is a much simpler non-keyed implementation than the last PR.  The last one essentially hand-rolled its own 30-line reconciler for the table rows, which was fast, and kind of cool that you can do it (since surplus is real DOM), but also kind of crazy.  This uses a (new) standard function mapSequentially plus the default reconciler, cutting about 25 lines from the code.  The old one came in 1-2% off of vanillajs, this one is more like 3-4%.
All my own apps use keyed-style rendering, so honestly, I hadn't even thought about this implementation until it came time to submit.  Surplus 0.5 was pretty much all aimed at improvements to keyed implementations.
Best
-- Adam

simpler surplus-v0.5.0-non-keyed implementation

---

.circleci/config.yml

Fixes #323.
I don't really like this solution (and avoided it at first) since it makes logs messier and it's harder to see how much time each command took, but having to account for $PATH being reset and resourced is a pain, _especially_ when it's changed by scripts.

Run all circleci node commands in the same shell

---

webdriver-ts/src/benchmarkRunner.ts

In chrome-launcher we have a [larger list ](https://github.com/GoogleChrome/chrome-launcher/blob/a48c47bd305e6ca137b6c94c7fc0b33660be71fe/flags.ts) of flags that we flip on for the browser. This adds in the ones I think make most sense for this project.

Add more automation/perf-friendly chrome flags

---

webdriver-ts/package.json
webdriver-ts/src/benchmarkRunner.ts
webdriver-ts/src/lighthouseConfig.ts

Thanks to your ping in https://github.com/krausest/js-framework-benchmark/issues/316#issuecomment-348297110 I spent some time on this so we could get a TTI metric calculated for you. Basically I'm just using Lighthouse to [process the perfLog](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#lighthouse-as-trace-processor).
I wasn't sure where this belongs between the CPU/MEM/Startup benchmarks, so I stuffed it into CPU. But the nice part here is that the only instrumentation changes are flipping on `enableNetwork`/`enablePage` and recording a few additional trace categories.
For now, I'm just logging the results to the console, though I'm sure you probably want to redirect the values somewhere more useful. 
As for the metrics themselves (and how they apply to this …

use lighthouse to calculate metrics from CPU benchmark

---

webdriver-ts/src/benchmarkRunner.ts
webdriver-ts/src/common.ts

Currently, if port 8080 is occupied, one of at least two things happen
- NixOS (possibly any Linux):   http-server will try 8081, 8082 and so on but the benchmark runner won't find it.
- MacOS: http-server will fail with `Error: listen EADDRINUSE 0.0.0.0:8080`
If one passes a custom port with `npm run start -- -p`, then it's also not found.

Allow supplying a custom port to benchmark runner

---

package.json

Turns out the `Error: listen EADDRINUSE 0.0.0.0:8080` error I mentioned in #333 is fixed by the new release of `http-server` : https://github.com/indexzero/http-server/issues/215
Of course, #333 is still needed when using anything but port 8080.

Bump http-server to 0.10.0

---

webdriver-ts/src/benchmarkRunner.ts

See #378. It seems that chrome driver doesn't kill off all sub-processes on windows if you call `quit` when there are still open windows. The result being that after a few benchmarks are run, the system starts bogging down terribly. This seems to work on my machine, but there is a comment in #378 suggesting that it may not cover all of the corners 100%.

close before quit to avoid zombie instances on windows

---

knockout-v3.4.2-ko-jsx-keyed/.babelrc
knockout-v3.4.2-ko-jsx-keyed/index.html
knockout-v3.4.2-ko-jsx-keyed/package.json
knockout-v3.4.2-ko-jsx-keyed/rollup.config.js
knockout-v3.4.2-ko-jsx-keyed/src/Main.js
knockout-v3.4.2-ko-jsx-keyed/src/template.jsx
webdriver-ts/src/common.ts

[https://github.com/ryansolid/ko-jsx](https://github.com/ryansolid/ko-jsx)
An alternate renderer for KnockoutJS that uses precompiled JSX to real DOM nodes with performance in mind. I hope will consider adding it to the benchmark suite.
Thanks.

Add ko-jsx

---

frameworks/solid-js-v0.0.8-keyed/.babelrc
frameworks/solid-js-v0.0.8-keyed/index.html
frameworks/solid-js-v0.0.8-keyed/package.json
frameworks/solid-js-v0.0.8-keyed/rollup.config.js
frameworks/solid-js-v0.0.8-keyed/src/app.jsx
frameworks/solid-js-v0.0.8-keyed/src/main.js
webdriver-ts/src/common.ts

[Solid.js](https://github.com/ryansolid/solid) is a new render library built on ES2015 proxies and precompiled JSX native DOM expressions.
Please consider adding it.

Add solid-js v0.0.8

---

frameworks/vanillajs-wc-keyed/index.html
frameworks/vanillajs-wc-keyed/package.json
frameworks/vanillajs-wc-keyed/src/main.js
webdriver-ts/src/common.ts

This implementation should show performance overhead of WebComponents. It is implemented in imperative VanillaJS style.
Works in Chrome >= 67 ([Customized built-in elements](https://www.chromestatus.com/feature/4670146924773376))

Add WebComponents flavoured VanillaJS implementation

---

frameworks/halogen-v2.1.0-non-keyed/package.json
frameworks/polymer-v2.0.0-non-keyed/package.json
frameworks/pux-v11.0.0-non-keyed/package.json
frameworks/thermite-v4.0.0-non-keyed/package.json

Bower deprecated and removed their old registry at http://bower.herokuapp.com/ and so now only 1.8.4 will work

Update bower to fix CI

---

webdriver-ts/src/benchmarks.ts
webdriver-ts/src/common.ts
webdriver-ts/src/forkedBenchmarkRunner.ts

supersedes #410 (split into a dedicated banch)
i'm working on an alternate results builder that's faster and doesn't require dependencies of 110MB and 13,000 files.
i noticed that the generated json results files did not conform to the same naming conventions, which makes the classification code more hairy. looks like this was an omission when merging/adjusting the Lighthouse metrics.

fix benchmark numbering and naming

---

results-ui/package.json
results-ui/src/build.js
results-ui/src/style.css
results-ui/src/ui.js
webdriver-ts/src/benchmarks.ts
webdriver-ts/src/common.ts
webdriver-ts/src/forkedBenchmarkRunner.ts

Hi @krausest,
This is a from-scratch implementation of an interactive results UI. This work builds on top of the necessary minor tweaks in #418.
The original motivation for this was to reduce `node_modules` bloat in `webdriver-ts-results` (~100MB, ~13,000 files) and perhaps improve build times, bundle size as well as boost UI performance. I'm pleased to report that the final result has surpassed my original expectations by a wide margin.
Full feature parity with `webdriver-ts-results` was not a goal, so some things got the axe:
- **Use median instead of mean** - recent improvements in the benchmark runner have made the differences mostly irrelevant
- **Separate keyed and non-keyed** - the ability to display keyed and non-keyed frameworks in the same table is gone
- **Compare with...** - i …

new results-ui

---

frameworks/keyed/react-mobX/src/Store.es6.js

Using `spliceWithArray` (a splice that don't needs spreading, which can cause issues in some JS engines if the collections is large) instead of concat fixes the issues (atm still unclear why, I could'nt reproduce the issue in a unit test). 
Also made the store more idiomatic by never replacing the `data` property, but always updating it
Fixes #427

Fixed issue #427: MobX test not working correctly

---

frameworks/keyed/hyperapp/package.json
frameworks/non-keyed/hyperapp/package.json

Updating hyperapp to the latest: v1.2.9.
There were some performance optimizations since 1.2 (the current benchmark version), so I'm very interested in seeing how it does.

Hyperapp update to 1.2.9

---

frameworks/keyed/vanillajs/src/Main.js
frameworks/non-keyed/vanillajs/src/Main.js

After seeing how much of difference this seems to make for some libraries thought I'd see if it was worth it.  This commit changes the createRow function into a domc-esque node clone:
```js
createRow(data) {
const tr = rowTemplate.cloneNode(true),
td1 = tr.firstChild,
a2 = td1.nextSibling.firstChild;
tr.data_id = data.id;
td1.textContent = data.id;
a2.textContent = data.label;
return tr;
}
```
This didn't make much of a difference on my computer, but at minimum this can be a comparison point.

Vanillajs use cloneNode instead of document.createElement

---

frameworks/keyed/react-easy-state/package.json

Fixes https://github.com/krausest/js-framework-benchmark/pull/465. easy-state was stuck with a beta version of webpack 4, which had some issues. I updated the webpack version to match with the other react implementations. (I think Redux is also behind, but I didn't want to touch it).

fix build process for react-easy-state (bump webpack)

---

frameworks/keyed/solid/package.json

Updated Solid to 0.1.2.
Seriously this benchmark is the best. After seeing how strangely variable Solid results were on the 16x slowdown select I realized a pretty serious performance issue in my selection operator where I was re-evaluating the whole list on every select needlessly.

Fix Solid Select performance

---

.travis.yml

Cloning the last 700 commits seems a bit much or is there a (good) reason?
The last 5 commits should be sufficient and we get faster clone times.

ci: decrease Git clone depth

---

frameworks/keyed/ko-jsx/package.json
frameworks/keyed/ko-jsx/src/Main.js
frameworks/keyed/ko-jsx/src/template.jsx
frameworks/keyed/mobx-jsx/package.json
frameworks/keyed/mobx-jsx/src/main.jsx
frameworks/keyed/solid/package.json
frameworks/keyed/solid/src/main.jsx

Pretty major change to the API of the underlying renderer where it is no longer automatically wrapping every expression. This prompts a new release for all 3 of solid, ko-jsx, mobx-jsx.  Some decent memory improvements for the first 2 but mobx-jsx doesn't seem to have really benefited from this update.
Also an even more significant update to solid to reduce API surface, and code, and increase compatibility with libraries like S.js and Surplus, at what I figure should be a noticeable performance change (it now wraps with ES6 proxies in all cases along the whole state tree which should have an overhead). As to the suggestions out of the setting a baseline discussion(#430) I'm attempting something similar to @localvoid  event delegation example API. I'm still sort of out on it, as it seems …

Updates to solid, ko-jsx, mobx-jsx

---

frameworks/keyed/ivi/package.json
frameworks/keyed/ivi/src/main.js

- Removed all crappy "advanced" optimizations from the benchmark implementation that were discussed in [this issue](https://github.com/krausest/js-framework-benchmark/issues/430).
- Reconciliation algorithm were completely reimplemented from scratch.
- Composition model is now even more expressive than React composition model (https://codesandbox.io/s/k9m8wlqky3).
- Virtual DOM is now completely immutable.
- Fragments.
- Key namespaces to prevent collisions of keys.
This implementation should be slower in some test cases and consume more memory than the previous one mostly because it is now implemented in almost exactly the same way as react-redux implementation.

Update ivi to 0.20.0

---

frameworks/keyed/react-redux/package.json

- Updated react-redux to 6.0.0, it is now using modern Context API
- Redux version is captured from `react-redux` package instead of `redux`

Update react-redux to 6.0

---

frameworks/keyed/ko-jsx/package.json
frameworks/keyed/ko-jsx/src/template.jsx
frameworks/keyed/mobx-jsx/package.json
frameworks/keyed/mobx-jsx/rollup.config.js
frameworks/keyed/mobx-jsx/src/main.jsx
frameworks/keyed/solid/package.json
frameworks/keyed/solid/src/main.jsx

Please merge this update to the latest version of these libraries.
- Reduced build size
- Centralized reconciliation for all libraries in renderer runtime, (based on Stage-0)
- Added support for JSX Fragments in List reconciliation
- Further reduced and streamlined Solid API
- Changed to React Hooks inspired API
- Added a compact Falcor inspired path API to Solid setState
- Removed many mostly useless micro optimizations from implementations that hurt readability/compactness
- Updated MobX implementation to use production mode.
I'm hoping none of this has a negative performance impact, but centralized reconciliation will lend to easier time of optimizing in the future.

Update Solid, ko-jsx, mobx-jsx

---

frameworks/keyed/hyperhtml/package.json
frameworks/keyed/hyperhtml/rollup.config.js
frameworks/keyed/hyperhtml/src/index.js

Not only the current version of _hyperHTML_ is way outdated, I have also noticed that competitors are allowed to use native ES2015 syntax without any transpiled penalization.
Well, I guess it's time to compare keyed _hyperHTML_ for real 😃

Update hyperHTML to 2.25.4

---

frameworks/keyed/lighterhtml/src/index.js
frameworks/non-keyed/lighterhtml/src/index.js

The following changes has been made:
* the keyed version of the test shouldn't create new objects each time otherwise the key gets lost for no reason
* the click event prevents defaults and stops its propagation to grant nothing else is affected while benchmarking

Update lighterhtml test

---

frameworks/keyed/lighterhtml/package.json
frameworks/keyed/lighterhtml/rollup.config.js
frameworks/non-keyed/lighterhtml/package.json
frameworks/non-keyed/lighterhtml/rollup.config.js

First of all, thank you so much for your patience.
I have investigated a bit further possible bottlenecks when it comes to the selection, and the only thing that came up is that addressing `className` instead of dealing with a `class` `Attribute` node might place _lighterhtml_ slightly higher in the table (in terms of faster, so ... moving to the left).
With the promise that I won't change/PR anything else for a little while since there's literally nothing else I could optimize in the current _lighterhtml_ library (it's eventually a core change that would take much longer to land), please consider updating, for the last time, this library.
Thank you!

Update lighterhtml to 0.8.10

---

frameworks/keyed/lighterhtml/index.html
frameworks/keyed/lighterhtml/package.json
frameworks/keyed/lighterhtml/rollup.config.js
frameworks/keyed/lighterhtml/src/index.js
frameworks/non-keyed/lighterhtml/index.html
frameworks/non-keyed/lighterhtml/package.json
frameworks/non-keyed/lighterhtml/rollup.config.js
frameworks/non-keyed/lighterhtml/src/index.js

Turns out that minifying HTML is somehow key to score better at this benchmark.
I know I've promised I wouldn't have changed the library, and indeed I just changed the rollup config.
At this point there's really nothing else I can do, except eventually find out slow paths and improve, but for now I just want a fair comparison with the major competitor.
Thanks again for your patience.

Update lighterhtml bundle + minifyHTML

---

frameworks/keyed/lit-html/src/index.js
frameworks/non-keyed/lit-html/src/index.js

This is the same as PR https://github.com/krausest/js-framework-benchmark/pull/521, but without the controversial change involving directly setting a class on the table row.
A few simplifications to the lit-html benchmark implementations:
* Minor style updates (semicolons etc.).
* Update `select` and `label` properties in-place and remove `guard` directive, instead of creating new row objects every time.
* Remove some unnecessary attributes and use `closest()` to find the action and row id.
* <strike>Directly update row class on select instead of forcing an unnecessary render.</strike>
cc @justinfagnani @rictic @CaptainCodeman

Simplify lit-html benchmark code (without direct DOM manipulation)

---

frameworks/keyed/ko-jsx/package.json
frameworks/keyed/ko-jsx/src/Main.js
frameworks/keyed/ko-jsx/src/template.jsx
frameworks/keyed/mobx-jsx/package.json
frameworks/keyed/mobx-jsx/src/main.jsx
frameworks/keyed/solid/package.json
frameworks/keyed/solid/src/main.jsx

Libraries are going to take a little bit of a hit on raw rendering with this one. Lots of feature enhancements, no specific focus on performance for this benchmark. Highlights:
* Full Support for JSX Fragments/Array in Control Flow, Direct Nested Multi-Level
* Control Flow as top level node and children expression wrapping optional
* Multi-mode Reconciler Add-on to do data diffing to support large data snapshots (DBMon, UIBench)
* Non-JSX option: HyperScript syntax run-time wrapper (although limited usefulness as skips compiler which does most of the heavy lifting)
* Implicit Event Delegation(I think, I don't even know anymore), with semi-synthetic events, support for composed Shadow DOM events and Custom Events. Follows Inferno convention of camelCase -> delegate and lowercase -> direct …

Update Solid, KoJSX, and MobXJSX v0.4.0

---

frameworks/non-keyed/sifrr/elements/main/element.html

From https://github.com/krausest/js-framework-benchmark/pull/516#issuecomment-464866673

Fix rule violation in sifrr

---

frameworks/keyed/reason-react/.gitignore
frameworks/keyed/reason-react/bsconfig.json
frameworks/keyed/reason-react/index.html
frameworks/keyed/reason-react/package.json
frameworks/keyed/reason-react/src/Button.re
frameworks/keyed/reason-react/src/Index.re
frameworks/keyed/reason-react/src/Jumbotron.re
frameworks/keyed/reason-react/src/Main.re
frameworks/keyed/reason-react/src/Row.re
frameworks/keyed/reason-react/src/Util.re
frameworks/keyed/reason-react/webpack.config.js

This is a (mostly) idiomatic implementation in ReasonML using ReasonReact.
- It uses the `option` type for seeing if a row is selected rather than just having 0 be a magic number for 'nothing selected', or just never resetting it if a row gets deleted like most other implementations
- I did implement the "update every 10th row" using an inplace method but it felt like a bit of a hack so I've left it in there but commented out.
- The `Row` component had to be a `reducerComponent` even though it is pretty much stateless - this is so that it can properly use `shouldUpdate` rather than rerendering all the time
The JSX (and the webpack config) is pretty much just copied from the various react implementations and changed to fit with the Reason syntax. Performance seems to be roughly the same as …

Add ReasonReact implementation

---

frameworks/keyed/ko-jsx/package.json
frameworks/keyed/mobx-jsx/package.json
frameworks/keyed/solid/package.json

I believe I've found the culprit to the issue found in #559 . A too strict null check lead to unoptimized clear all path for all 3 libraries. This pull requests updates the libraries to version with the fix.

Fix performance regression in Solid, MobX JSX, and Knockout JSX

---

frameworks/keyed/sinuous/.eslintrc.yml
frameworks/keyed/sinuous/index.html
frameworks/keyed/sinuous/package.json
frameworks/keyed/sinuous/rollup.config.js
frameworks/keyed/sinuous/src/main.js

Adds [Sinuous](https://github.com/luwes/sinuous/) v0.6.0.
Thanks to @ryansolid, @adamhaile and @Freak613 for crucial code in this lib,  
also @developit and @jviide for [htm](https://github.com/developit/htm)!
The idea was to 
- keep the original [hyperscript](https://github.com/hyperhype/hyperscript) idea alive 
- with a better [observable](https://github.com/luwes/sinuous/tree/master/packages/sinuous/observable) API 
- favor template literal over JSX
- no "precompilation", `h` tag is the lowest it can get
- keep bundle size small for lightweight components
A minimal Sinuous app without a list is `< 2kB` gzip
- developer experience++, less library specialized concepts, plain JS feel
Results:

Add sinuous-v0.6.0-keyed

---

frameworks/keyed/redom/src/app.js
frameworks/non-keyed/redom/src/app.js

Tiny improvement for RE:DOM:
- Avoids modifying the class list if not needed.
- Storing `this.remove` was probably not needed.
My measurement have high statistical errors, but for "select row" the improvement is likely statically significant:
| Before                                                                                                        |                                                     After                                                     |
|---------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------:|
| ![old_2](https://user-images.githubusercontent.com/3620703/58127081-d23e5000-7c14-11e9-973f-860a5498cd2 …

[redom] avoid unnecessary classlist updates

---

frameworks/keyed/sinuous/package.json
frameworks/keyed/sinuous/src/main.js

This should improve memory use for reactive libraries w/ semi-automatic cleanups.
The parent computations take care of that.
Thanks to @ryansolid for detecting this issue!

Update sinuous to v0.7.1

---

frameworks/keyed/sinuous/package.json
frameworks/keyed/sinuous/src/main.js

Under the hood this update does a few things:
- Adds a `template` feature to get the perf benefits of `element.cloneNode()` https://github.com/luwes/sinuous/pull/4
- Optimizes the clear method with `element.textContent = ''` if there are no siblings.
This change also makes the "selection" fully data driven.
https://github.com/krausest/js-framework-benchmark/compare/master...luwes:sinuous?expand=1#diff-625243bf69109917f89eb7c1adf2cef2R58

Update Sinuous to v0.8.0 and add data selection

---

frameworks/keyed/react-redux-hooks/src/main.jsx

[react-redux v7.1.0-alpha.5](https://github.com/reduxjs/react-redux/releases/tag/v7.1.0-alpha.5) removed `deps` array as a second argument.

Fix perf regression in react-redux

---

frameworks/non-keyed/gruu/index.html
frameworks/non-keyed/gruu/package.json
frameworks/non-keyed/gruu/src/main.es6.js

Fixes #578 for gruu framework, meaning aria-hidden="true" is now correctly added to span

Upgrade gruu version

---

frameworks/keyed/sinuous/package.json
frameworks/keyed/sinuous/src/main.js

Added an optimization where `sinuous/template` can update text nodes w/ `Text.data` instead of `parent.textContent`.
Also changes that the top element in a template can access the props via `node.props` instead of `node.data` which could collide with the native text node `.data` property.

Update Sinuous v0.9.2

---

.circleci/config.yml

This is required for Lighthouse.
> Lighthouse requires Node 10 LTS (10.13) or later.
I know Docker is used now but would still be nice to see CI passing :)
```js
/home/circleci/project/webdriver-ts/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:35
class URLShim extends URL {
^
ReferenceError: URL is not defined
```
Fixes #593

Update CircleCI version to Node 10

---

frameworks/keyed/sinuous/package.json
frameworks/keyed/sinuous/rollup.config.js
frameworks/keyed/sinuous/src/main.js

Made a lot of updates mostly to reduce bundle size and fix the weird event syntax for non-observable event listeners. I also removed a lot of specialized attributes/properties which might come back if anyone requests them but I prefer to have the 1:1 with JS element properties if possible. `attrs` is an exception, not sure if everything can be done with properties besides `aria-`, `data-`. 
I'm attaching the changelog since `v0.9.2` for reference.
Hoping it wouldn't affect performance too much.
- Prioritized string and numeric values for `insert`.
- Removed array to node support in `insert`. Save some bytes.
- Fixed mixed exports
It's not recommended to have a default AND named exports
- Removed multi expressions
- Added minified browser version `.min.js`.
- Removed shorthand tag parser …

Update Sinuous v0.11.4

---

frameworks/keyed/inferno/package.json
frameworks/keyed/inferno/src/controller.jsx
frameworks/non-keyed/inferno/package.json
frameworks/non-keyed/inferno/src/controller.jsx

Updated Inferno to 7.2.1, because 7.2.0 had a bug where events were not patched correctly.
Removed old comments from inferno controller.jsx file and fixed wrong title in non-keyed implementation. Also removed `$HasVNodeChildren` optimization flag because its done automatically by JSX plugin.

Updated to Inferno 7.2.1 and clean up controller.jsx

---

frameworks/keyed/mikado/index.html
frameworks/keyed/mikado/package.json
frameworks/keyed/mikado/src/bench.js
frameworks/keyed/mikado/src/config.js
frameworks/keyed/mikado/src/data.js
frameworks/keyed/mikado/src/main.js
frameworks/keyed/mikado/src/template.html
frameworks/keyed/mikado/src/type.js
frameworks/keyed/mikado/task/build.js
frameworks/keyed/mikado/task/compile.js
frameworks/keyed/mikado/webpack.config.js
frameworks/non-keyed/mikado/index.html
frameworks/non-keyed/mikado/package.json
frameworks/non-keyed/mikado/src/bench.js
frameworks/non-keyed/mikado/src/config.js
frameworks/non-keyed/mikado/src/data.js
frameworks/non-keyed/mikado/src/main.js
frameworks/non-keyed/mikado/src/template.html
frameworks/non-keyed/mikado/src/type.js
frameworks/non-keyed/mikado/task/build.js
frameworks/non-keyed/mikado/task/compile.js
frameworks/non-keyed/mikado/webpack.config.js

Hello, I would like to add the Mikado templating library. First of all thanks to this community for providing such a good comparison playground. I need some help to find out what kind of functionality is accepted and which not. I read a lot within the issues but at the end I'm not really sure what the rules are.
The current implementation is able to restore all states when rendering would be forced.

ADD Mikado keyed/non-keyed

---

frameworks/keyed/sinuous/package.json
frameworks/keyed/sinuous/src/main.js

Lots of changes but shouldn't affect performance too much. Here is the changelog since v0.12.6.
This change should affect perf positively:
- Disable `observable` cleaning by default in `map` for repeated `template`'s.
The rest probably negatively 😄 size increased a bit too 😢 
https://github.com/luwes/sinuous/blob/master/CHANGELOG.md
- Changed map mini import to be `import { map } from 'sinuous/map/mini'` instead of `import { mini } from 'sinuous/map'`.
- Re-named variables in `map` and golfed down the bundle from 1.45kB to 1.19kB, also by removing the fast path for swap backward and swap forward.
- Added basic `hydrate` feature [#36](https://github.com/luwes/sinuous/pull/36)
- Disable `observable` cleaning by default in `map` for repeated `template`'s.
- Prevented running duplicate nested …

Upgrade Sinuous to v0.15.1

---

frameworks/keyed/ko-jsx/package.json
frameworks/keyed/ko-jsx/src/template.jsx
frameworks/keyed/mobx-jsx/package.json
frameworks/keyed/mobx-jsx/src/main.jsx
frameworks/keyed/solid-signals/package.json
frameworks/keyed/solid-signals/src/main.jsx
frameworks/keyed/solid/package.json
frameworks/keyed/solid/src/main.jsx

Haven't updated for a while so thought I'd submit. There have actually been a lot of changes. Primarily:
* Removal of explicit `{( )}` syntax for dynamic bindings. Now a heuristic is used to determine if the binding could be dynamic. It simplifies things greatly for end users but requires a bit more diligence for getting optimal performance (ko-jsx, mobx-jsx hoist out their list mapping now in the implementation)
* Batching of computations. No longer are bindings guarenteed to be one per computation. This substantially removes overhead when have many bindings on nodes (not applicable here).
* More robustness around downstream conditional resolution. Some fine-grained libraries acted in unexpected ways under nested contexts dependent on different but related data. This added more size and …

Update Solid v0.13.0 (and KO JSX, MobX JSX)

---

frameworks/keyed/heresy/index.html
frameworks/keyed/heresy/package.json
frameworks/keyed/heresy/rollup.config.js
frameworks/keyed/heresy/src/index.js
frameworks/keyed/heresy/src/ui/app.js
frameworks/keyed/heresy/src/ui/button.js
frameworks/keyed/heresy/src/ui/row.js
frameworks/non-keyed/heresy/index.html
frameworks/non-keyed/heresy/package.json
frameworks/non-keyed/heresy/rollup.config.js
frameworks/non-keyed/heresy/src/index.js
frameworks/non-keyed/heresy/src/ui/app.js
frameworks/non-keyed/heresy/src/ui/button.js
frameworks/non-keyed/heresy/src/ui/row.js

The [heresy](https://github.com/WebReflection/heresy/#readme) project can perform both keyed and non-keyed updates through Custom Elements, via _lighterhtml_ engine, without name clashing and through simplified literal non-dom-coupled definition.
The project is close to reach v1 and I would like to compare it with other projects, even if Custom Elements re not super common in this benchmark.
Thanks for eventually considering this PR.

heresy: custom elements for lighterhtml

---

frameworks/keyed/lighterhtml/package.json
frameworks/keyed/lighterhtml/rollup.config.js
frameworks/keyed/lighterhtml/src/index.js
frameworks/non-keyed/lighterhtml/package.json
frameworks/non-keyed/lighterhtml/rollup.config.js
frameworks/non-keyed/lighterhtml/src/index.js

Thanks to _domdiff_ investigation and benchmarks, I've eventually found out what was making _lighterhtml_ way slower on the "_select rows_" part of the benchmark, and not only.
Turns out, a single `WeakMap` could compromise this benchmark [extra miles](https://jsperf.com/weakmaps-vs-arrays), and it's only via _domdiff_ PR that I could see where was my main bottleneck.
Meanwhile, both _domdiff_ and _domtagger_ has been updated to produce best possible results, so that _lighterhtml_ 2.0.6 should be (hopefully) right beside _lit-html_, as it uses a single WeakMap too.
This update would like to place _lighterhtml_ in a more fair place, so I hope it will get merged at some point.
Thanks again for your patience, and effort, with this project 👍

lighterhtml: dependencies update

---

frameworks/keyed/domdiff/package.json
frameworks/keyed/domdiff/src/index.js
frameworks/keyed/domdiff/src/utils.js
frameworks/non-keyed/domdiff/package.json
frameworks/non-keyed/domdiff/src/index.js
frameworks/non-keyed/domdiff/src/utils.js

For all the exact same reasons specified in https://github.com/krausest/js-framework-benchmark/pull/676, this is the ultimate change to drop `WeakMap` slowdown from the equation.

domdiff: final test-case update

---

frameworks/keyed/lighterhtml/package.json
frameworks/keyed/lighterhtml/rollup.config.js
frameworks/keyed/lighterhtml/src/index.js
frameworks/keyed/lighterhtml/src/jumbotron.js
frameworks/keyed/lighterhtml/src/table.js
frameworks/non-keyed/lighterhtml/package.json
frameworks/non-keyed/lighterhtml/rollup.config.js
frameworks/non-keyed/lighterhtml/src/index.js
frameworks/non-keyed/lighterhtml/src/jumbotron.js
frameworks/non-keyed/lighterhtml/src/table.js

This is the last thing I can change to have a better comparison (as in: more fair one).
As every other competing framework is using `item.id` to reference rows, and as each item lives as long as the database has it, I've finally found a way to not create O(n) WeakMap references, but just O(1) related to the data.
This provides the possibility to use the `item.id` in _lighterhtml_ too (and every other framework of mine, PRs will follow) so that instead of benchmarking WeakMap performance, we can now compare raw libraries logic/core/engines.
As result, and since there's literally nothing else I can do to make it faster so this is really my last update 'til 2020, the new keyed test drops the infamous _selectRow_ slowdown, placing _lighterhtml_ way up in the table.
Once again, thanks a lot …

lighterhtml: final test-case update

---

frameworks/keyed/ractive/src/main.ractive.html

Prior to 0.10, ractive didn't really support moving more than one item at a time, which means that the row swap only really worked for one item and the other was recreated. This is now possible, though not exactly an optimized case.
See #694

update ractive keyed row swap per #694

---

frameworks/keyed/reaml-preact/.gitignore
frameworks/keyed/reaml-preact/.ocamlformat
frameworks/keyed/reaml-preact/bsconfig.json
frameworks/keyed/reaml-preact/index.html
frameworks/keyed/reaml-preact/package.json
frameworks/keyed/reaml-preact/preact.js
frameworks/keyed/reaml-preact/rollup.config.js
frameworks/keyed/reaml-preact/src/Main.ml
frameworks/keyed/reaml-react/.gitignore
frameworks/keyed/reaml-react/.ocamlformat
frameworks/keyed/reaml-react/bsconfig.json
frameworks/keyed/reaml-react/index.html
frameworks/keyed/reaml-react/package.json
frameworks/keyed/reaml-react/rollup.config.js
frameworks/keyed/reaml-react/src/Main.ml

[Reaml](https://github.com/utkarshkukreti/reaml) is an OCaml/BuckleScript wrapper for React. My goal for submitting this is to show the overhead (both perf and size) vs optimized JS + React and JS + Preact to potential users.
Please let me know if I missed any step of the contributing guide!
(The canonical implementation of this lives [in the Reaml repo](https://github.com/utkarshkukreti/reaml/blob/master/examples/Jfb.ml); this is a copy of that file.)
(follow up to #699)

add reaml-react and reaml-preact

---

frameworks/keyed/vuerx-jsx/index.html
frameworks/keyed/vuerx-jsx/package.json
frameworks/keyed/vuerx-jsx/rollup.config.js
frameworks/keyed/vuerx-jsx/src/main.jsx

@yyx990803 posted that Vue 3's Reactive library was stand-alone so I couldn't help myself. Let's see how it does when not tethered to Vue 3's hybrid VDOM solution. Introducing [VueRX JSX](https://github.com/ryansolid/vuerx-jsx) (Vue JSX was already taken). It uses the DOM Expressions library to compile JSX down to optimized DOM statements and reactive bindings.
Quick tests show this Vue variation outperforms MobX, but does it have what it takes to go up against the VDOM heavy-weights like Inferno or ivi? We shall see.

Add VueRX JSX

---

frameworks/keyed/reagent/src/demo/main.cljs

This changes the implementation to only render the selected (and deselected) rows, instead of the whole list. Code is still idiomatic and matches what Reagent apps would normally do (though often using Re-frame which adds more state management tools over Reagent built-in features).
Also cleaned the code a bit, by removing performance measure calls. I guess they were there just to help development, other frameworks don't seem to have such. (89b546fe1b772e0f9f0b94da81b83513b6759e4b seems to have removed these calls for JS frameworks)

Optimize Reagent select row

---

frameworks/keyed/dojo/package.json
frameworks/keyed/dojo/src/Buttons.ts
frameworks/non-keyed/dojo/package.json
frameworks/non-keyed/dojo/src/App.ts
frameworks/non-keyed/dojo/src/Buttons.ts
frameworks/non-keyed/dojo/src/Row.ts
frameworks/non-keyed/dojo/src/Store.ts

Fixes the non-keyed version of Dojo and also upgrades both version to the latest release (7.0.0).
cc @krausest 
With regards to https://github.com/krausest/js-framework-benchmark/issues/742#issuecomment-634919576, we are working on improving the core support in the rendering engine which hopefully will be available  soon. I tested a draft implementation with the keyed check and it passed so should resolve the issue.
Resolves #742

Dojo: Update to dojo 7 and fix non-keyed impl

---

frameworks/keyed/react-mobX/package.json
frameworks/keyed/react-mobX/src/Main.jsx
frameworks/keyed/react-mobX/webpack.config.js

This fixes: https://github.com/mobxjs/mobx-react/issues/877
React became really slow after upgrading to 16.6+, which is caused by a bug in the default webpack minifier (https://github.com/facebook/react/issues/13987). This might apply to other React based frameworks as well. 
Also enabled ReactDOM batching support according to best practice.

Fixed MobX benchmark after upgrading by swapping minifier and enabling batching

---

webdriver-ts/src/common.ts
webdriver-ts/src/forkedBenchmarkRunner.ts
webdriver-ts/src/isKeyed.ts
webdriver-ts/src/webdriverAccess.ts

Allow using Shadow Dom for table row.
closes #753 
Requires:
- to use an autonomous custom element named `benchmark-row` with
a shadowRoot containing one HTMLTableRowElement
- to add set `useRowShadowRoot` to `true` in "js-framework-benchmark"
in the integration's package.json
After running some benchmarks, I'm pretty sure this doesn't change results when not using `useRowShadowRoot`. Yet,
results for "partial update", "swap rows" & "remove row"  seems wrong with shadow dom. I didn't find why, but to be fair I didn't spend a long time on this (for now, I only care about first time rendering). Any idea would be very welcome.
Here, `vanillajs-custom-el` is pretty much the same thing as `vanillajs-shadow`, except it doesn't use a shadow dom, and `shadow` includes some styles (which leads to …

(WIP) allow using shadow dom for table row element

---

frameworks/keyed/reaml-preact/package-lock.json
frameworks/keyed/reaml-preact/package.json
frameworks/keyed/reaml-react/package-lock.json
frameworks/keyed/reaml-react/package.json

Just updating all dependencies. The benchmark runs a tiny bit faster with the latest version of bs-platform (the `ml` -> `js` compiler) for me.

Update reaml dependencies

---

frameworks/keyed/ko-jsx/package-lock.json
frameworks/keyed/ko-jsx/package.json
frameworks/keyed/ko-jsx/rollup.config.js
frameworks/keyed/ko-jsx/src/Main.js
frameworks/keyed/ko-jsx/src/template.jsx
frameworks/keyed/mobx-jsx/package-lock.json
frameworks/keyed/mobx-jsx/package.json
frameworks/keyed/mobx-jsx/rollup.config.js
frameworks/keyed/mobx-jsx/src/main.jsx
frameworks/keyed/solid-state/package-lock.json
frameworks/keyed/solid-state/package.json
frameworks/keyed/solid-state/rollup.config.js
frameworks/keyed/solid-state/src/main.jsx
frameworks/keyed/solid/package-lock.json
frameworks/keyed/solid/package.json
frameworks/keyed/solid/rollup.config.js
frameworks/keyed/solid/src/main.jsx
frameworks/keyed/vuerx-jsx/package-lock.json
frameworks/keyed/vuerx-jsx/package.json
frameworks/keyed/vuerx-jsx/rollup.config.js
frameworks/keyed/vuerx-jsx/src/main.jsx

With this PR I remove all direct DOM manipulation. No `el.className = "danger"` anywhere. No clever DOM node caching using reactive memorization. Not even shortcutting the test by dirtying the data model with a selected on each row. All my libraries will be doing an inline `class={selected() === id ? "danger" : ""}` or equivalent from now on.
By doing so all my libraries will take a performance hit. But the front end of this benchmark has gotten a bit ridiculous with bending the expectation. I hope with this I can encourage others to remove shady not in the spirit of the test implementation pieces. But if not at least they can serve as an example.
----------------------------
That being said I'm looking forward to testing a new technique I've developed. Inspired by Recoil's …

Update DOM Expression Libraries and Remove all hacks

---

frameworks/keyed/react-easy-state/package-lock.json
frameworks/keyed/react-easy-state/package.json
frameworks/keyed/react-hooks/package-lock.json
frameworks/keyed/react-hooks/package.json
frameworks/keyed/react-mobX/package-lock.json
frameworks/keyed/react-mobX/package.json
frameworks/keyed/react-redux-hooks/package-lock.json
frameworks/keyed/react-redux-hooks/package.json
frameworks/keyed/react-redux/package-lock.json
frameworks/keyed/react-redux/package.json
frameworks/keyed/react-tracked/package-lock.json
frameworks/keyed/react-tracked/package.json
frameworks/keyed/react/package-lock.json
frameworks/keyed/react/package.json
frameworks/keyed/reaml-react/package-lock.json
frameworks/keyed/reaml-react/package.json
frameworks/keyed/reason-react/package-lock.json
frameworks/keyed/reason-react/package.json

Hi and thanks a lot for creating and maintaining this project!
I'm about to make a contribution for `react-rxjs` and I thought that maybe it would be a good idea to first upgrade all react-based contributions, so that they all use the latest version of both React and their own library.
Regarding `react-mobx` though, I have been able to upgrade React to version 17.0.1 without any issues. However, I haven't been able to upgrade `mobx` and `mobx-react`, because the latest versions that are not backwards compatible with the current implementation.
If you rather handle these upgrades yourself, no worries, I totally get it. If that's the case, when I send the `react-rxjs` contribution I will be using the same version of React 16 that all the other ones are using and I will upgrade when the …

Upgrade dependencies on react contributions

---

frameworks/keyed/ember/app/components/my-table.js
frameworks/keyed/ember/app/components/table-row/template.hbs
frameworks/keyed/ember/app/templates/components/my-table.hbs
frameworks/keyed/ember/app/utils/benchmark-helpers.js

related to https://github.com/krausest/js-framework-benchmark/pull/814

bugfix: ember issue #800

---

frameworks/keyed/preact/package-lock.json
frameworks/keyed/preact/package.json
frameworks/keyed/preact/src/Row.jsx
frameworks/keyed/reaml-preact/package-lock.json
frameworks/keyed/reaml-preact/package.json
frameworks/keyed/riot/package-lock.json
frameworks/keyed/riot/package.json
frameworks/keyed/svelte/package-lock.json
frameworks/keyed/svelte/package.json
frameworks/non-keyed/riot/package-lock.json
frameworks/non-keyed/riot/package.json
frameworks/non-keyed/svelte/package-lock.json
frameworks/non-keyed/svelte/package.json

Updated:
- preact & realm-preact to 10.5.5
- riot to 5.0.0
- svelte to 3.29.4

Update preact, riot and svelte to latest

---

frameworks/keyed/react-hooks/src/main.jsx

As I mentioned in [this comment](https://github.com/krausest/js-framework-benchmark/pull/823#issuecomment-729622921): I'm quite confident that using `useCallback` inside that `Row` component can only be detrimental for performance.

remove bogus useCallback from react-hooks implementation

---

frameworks/keyed/vue-next/index.html
frameworks/keyed/vue-next/package.json
frameworks/keyed/vue-next/src/App.vue
frameworks/non-keyed/vue-next/index.html
frameworks/non-keyed/vue-next/package.json
frameworks/non-keyed/vue-next/src/App.vue

Existing tests were based beta version and since then Vue 3 has been released, with many improvements. This patch upgrades yo latest Vue3

Vue.next updated to 3.0.2

---

README.md
webdriver-ts/src/common.ts
webdriver-ts/src/isKeyed.ts

I included a check for the gzipped files as per #829. 
The check returns a `FrameworkVersionInformationError` which is not really the right name for it, but it's what the function returns if it doesn't find a `package.json` file so I figure it is the correct thing to return, but perhaps it should be renamed to something which captures the purpose better, like `Framework[Implementation/Installation/Configuration]Error` or something?
I wanted to mention gzip files in the README, but got a bit carried away and made these changes:
1. Put headings to correct sizes relative to others
2. Grouped all the "how to use this tool" sections together, and all the "how to contribute a framework" together - as they were previously a bit scattered.
4. Fixed some obvious typos, and added missing `:` before …

Gzip check

---

frameworks/keyed/bdc/package.json
frameworks/keyed/bdc/src/app.js
frameworks/non-keyed/bdc/package.json
frameworks/non-keyed/bdc/src/app.js

There was no good excuse for having this in before.

Fix explicit use of requestAnimationFrame in BDC

---

frameworks/keyed/alpine/package.json
frameworks/keyed/hyperapp/package.json
frameworks/keyed/inferno/package.json
frameworks/keyed/preact/package.json
frameworks/keyed/reaml-preact/package.json
frameworks/keyed/riot/package.json
frameworks/keyed/sinuous/package.json
frameworks/keyed/vue/package.json
frameworks/non-keyed/inferno/package.json
frameworks/non-keyed/riot/package.json
frameworks/non-keyed/vue/package.json

Update `alpine`, `hyperapp`, `inferno`, `preact`, `riot`, `sinuous` and `vue` to latest version.

Update Preact, Vue, Riot and others

---

README.md

running `npm install` potentially overrides the `package-lock` file causing unplanned changes.
`npm ci` instead leverages the `package-lock` file to create exactly the same node modules setup.

docs(README): suggest running `ci` instead of `install`

---

frameworks/keyed/heresy/package.json
frameworks/keyed/hyperhtml/package.json
frameworks/keyed/lighterhtml/package.json
frameworks/keyed/lit-html/package.json
frameworks/keyed/s2/package.json
frameworks/keyed/sifrr/package.json
frameworks/keyed/sinuous/package.json
frameworks/keyed/uhtml/package.json

I'm not stoked about this PR but fair is fair. If we are going to mark some #801 we should mark them all. I only reviewed keyed implementations and skipped ones with 694 or 772 as I figure those can be re-eval'd should they change. And of course I skipped Marionette as it's basically a 772. I can see how the argument could be made otherwise since it doesn't manipulate the DOM but creates everything with DOM APIs, but there is no "template". It's also an 801 too as the events are definitely explicitly delegated but without template syntax or whatever I don't even know how to categorize it if isn't clearly 772.

Mark some 800/801s

---

frameworks/keyed/lit/index.html
frameworks/non-keyed/lit/index.html

PR to resolve this issue: https://github.com/lit/lit/issues/1855
Removed the polyfill.
Is there any reason we'd want to keep the polyfill?
- In [many cases](https://lit.dev/docs/tools/requirements/#modern-browser-breakdown) it shouldn't be required.
I ran `npm run check keyed/lit` and `npm run check non-keyed/lit`. I didn't benchmark the non-keyed/lit, but did benchmark keyed/lit.

Remove Lit polyfill

---

frameworks/keyed/react-focal/.prettierrc
frameworks/keyed/react-focal/index.html
frameworks/keyed/react-focal/package-lock.json
frameworks/keyed/react-focal/package.json
frameworks/keyed/react-focal/src/index.tsx
frameworks/keyed/react-focal/tsconfig.json
frameworks/keyed/react-focal/webpack.config.js

Here is a benchmark for [@grammarly/focal library](https://github.com/grammarly/focal).
All local tests are passed 
```bash
~/Projects/js-framework-benchmark/webdriver-ts % npm run check keyed/react-focal
> webdriver-ts@1.0.0 check /Users/ostap.chervak/Projects/js-framework-benchmark/webdriver-ts
> cross-env LANG="en_US.UTF-8" node dist/isKeyed.js "keyed/react-focal"
args.framework undefined true
http://localhost:8080/frameworks/keyed/react-focal/package-lock.json
Frameworks that will be checked react-focal-v17.0.1 + 0.8.5-keyed
react-focal-v17.0.1 + 0.8.5-keyed is keyed for 'run benchmark' and keyed for 'remove row benchmark' and keyed for 'swap rows benchmark' . It'll appear as keyed in the results
```

React + @grammarly/focal@0.8.5 benchmark

---

frameworks/keyed/uhtml/package-lock.json
frameworks/keyed/uhtml/package.json
frameworks/keyed/uhtml/rollup.config.js
frameworks/keyed/uhtml/src/index.js
frameworks/keyed/uhtml/src/jumbotron.js
frameworks/keyed/uhtml/src/table-delegate.js
frameworks/keyed/uhtml/src/table-tr.js
frameworks/non-keyed/uhtml/package-lock.json
frameworks/non-keyed/uhtml/package.json
frameworks/non-keyed/uhtml/rollup.config.js
frameworks/non-keyed/uhtml/src/index.js
frameworks/non-keyed/uhtml/src/jumbotron.js
frameworks/non-keyed/uhtml/src/table-delegate.js

The following MR provides:
* both delegate and tr based version of the keyed version
* keyed benchmark uses the delegate, as discussed in https://github.com/krausest/js-framework-benchmark/pull/878
* all dependencies and dev dependencies have been updated
* new syntax showcase has been added
* changed the ugly uHTML for non keyed, made it uhtml
Thanks for considering this update.

Update uhtml to v2.7.5

---

frameworks/keyed/solid-state/package-lock.json
frameworks/keyed/solid-state/package.json
frameworks/keyed/solid-state/src/main.jsx
frameworks/keyed/solid/package-lock.json
frameworks/keyed/solid/package.json
frameworks/keyed/solid/src/main.jsx

I've been doing some last min pre-release performance checking for Solid's 1.0 release. This is likely one of the last Release Candidates so it's a good time to verify any regressions etc, although admittedly as soon as 1.0 comes out I'm probably back here again.
That being said I think I've made performance improvements. It's pretty hard to gain ground here but running on the Macbook Air with no slowdowns showed me slightly more accented bottlenecks that I was able to address on Remove Row and Clear Rows. Whether that translates elsewhere remains to be seen. I might be reaching the limits of improvement here in terms of approach.
Reducing the gap with Mikado has been a subgoal, but a general-purpose subscription system is going to have difficulty breaking through. I've concluded:
* …

Update Solid to 1.0.0

---

frameworks/keyed/uhtml/package-lock.json
frameworks/keyed/uhtml/package.json
frameworks/keyed/uhtml/src/index.js
frameworks/keyed/uhtml/src/table.js

This MR applies the following changes:
* previous techniques are preserved
* the 801 "*issue*" has been removed
* new helpers landed as dependency update
* some logic has been moved (as implementation detail) to the helper
* events are attached directly to the element, like others without 801 do
* no trickery beyond the events ... these are *not* a top level delegate, even if that would give more perf boost
Thanks for considering this MR 👋

Update uhtml dependencies and logic

---

frameworks/keyed/fntags/package-lock.json
frameworks/keyed/fntags/package.json

I was using setTimeout to schedule an async task instead of creating a Promise because I'm a noob. I'm expecting this version to be a bit quicker than the last one.

update fntags to 0.1.7

---

frameworks/keyed/svelte/src/Main.svelte

Svelte does not currently [1] remove purely whitespace text nodes like
most other frameworks do, which causes noticeable performance impact
when benchmarking creating thousands of rows.
This commit manually fixes that so that the generated HTML is closer to
the competing implementations, using a workaround mentioned in [1].
On my system, all the benchmarks involving creation of rows run ~5%
faster with this change and the overall geometric mean improves from
around 1.28 to 1.25.
[1]: https://github.com/sveltejs/svelte/issues/6540

keyed/svelte: optimize hot loop by eliminating extra whitespace nodes

---

frameworks/keyed/sinuous/package.json

This upgrades Sinuous to the latest version.
- Reverts to the old map diff algo which performed a lot better
https://github.com/luwes/sinuous/pull/192

Upgrade Sinuous v0.28.0

---

frameworks/keyed/voby/package.json
frameworks/keyed/voby/src/main.tsx

I implemented a few optimizations here and there, maybe they'll make a measurable difference in the benchmark 🤔

Updated Voby to 0.2.0

---

frameworks/keyed/voby/package.json
frameworks/keyed/voby/src/main.tsx

I added some more optimizations, cleaned up the code a bit, and now I'm storing the "selected" state in the model. 
I think performance might be slightly better, as N-1 no longer necessary observables have been deleted in the process, but the noise of measuring is probably higher than that anyway.
Fingers crossed now, unless there are some issues or decent optimizations missing, the framework is "done". I'll probably tweak it a little bit once I start using it and know where the pain points are though.

Updated Voby to v0.7.0

---

frameworks/keyed/voby/package.json
frameworks/keyed/voby/src/main.tsx

- v0.12 had faster clearing but it left some work to do in the future potentially, now clearing may be a bit slower but there's no leftover work or risks of memory leaks, though I had to resort to some manual disposition to gain some of that performance back.
- A fairly important bug got fixed, it just made things less efficient though, the framework still worked correctly as far as I can tell.
- The cache behind the crucial For component is more optimized.
- The framework is now tree shakeable, and its core is mangled. 
Basically the framework should do better on memory usage and startup tests, but it may be a bit slower.
Apparently today/tomorrow Chrome 100 will be released, I hope I submitted this in time for that.

Updated Voby to v0.14.0

---

frameworks/keyed/voby/package-lock.json
frameworks/keyed/voby/package.json

With this update the framework should gain back some of the performance that was lost with v0.18.
Locally I'm seeing 1.11 -> 1.09 for the templated version (this version), and 1.25 -> 1.17 for the version that doesn't use `template` which seems pretty good to me.

Updated Voby to v0.18.1

---

frameworks/keyed/ui5-webcomponents/package-lock.json
frameworks/keyed/ui5-webcomponents/package.json
frameworks/non-keyed/ui5-webcomponents/package-lock.json
frameworks/non-keyed/ui5-webcomponents/package.json

Hi,
the original benchmark result had a sub optimal result on select row as discussed in #1016 
ui5-webcomponents provides an updated version with a fix which no longer uses lit-html static by default,
only when scoping enabled.
This PR is using the latest version of ui5-webcomponents.

update ui5-webcomponents to 1.3.1

---

frameworks/keyed/voby/package-lock.json
frameworks/keyed/voby/package.json
frameworks/keyed/voby/src/main.tsx

- Some internal changes, nothing that should make much of an impact here I think, the framework is more granularly tree-shakeable, but esbuild can't take advantage of that it seems.
- Apparently esbuild was outputting sloppy-mode code, now I forced it to output the `"use strict";` directive, maybe that could have an impact, but probably not I guess.

Updated Voby to v0.23.2

---

frameworks/keyed/voby/package.json
frameworks/keyed/voby/src/main.tsx

Some internal fixes and new APIs, the main thing relevant to the benchmark I guess is that now the framework tree-shakes a little better. Nothing drastic though.
I hope this will be the last PR for a while, the future main ones should be about supporting stores, which may have a positive impact on clearing actually (and maybe a negative one on everything else), and about supporting automatic application of the "template" function via a bundler plugin, which could be kind of a big improvement, but irrelevant for the benchmark I think.

Updated Voby to v0.25

---

frameworks/keyed/uhtml/package-lock.json
frameworks/keyed/uhtml/package.json
frameworks/non-keyed/uhtml/package-lock.json
frameworks/non-keyed/uhtml/package.json

The 3.0.0 version of *uhtml* had an [issue with partial content](https://github.com/WebReflection/uhtml/issues/64) so that every node, even single nodes, where created as document fragment and retained as such.
Version 3.0.1 patched that behavior, and it's been rock-solid/robust for long time now so that I think it's fair to have the latest, not leak and not overhead prone version of this module.
Thank you.

Updated uhtml to the patcehd 3.0.1

---

server/index.js

This PR add `webdriver-ts-results ` directory into list static directory in express server. Due to this changes not present - result page was not visible.

expose webdriver-ts-results folder as static directory

---

server/index.js

NPM has new `package-lock.json` formats (v2 and v3), which means if you recreate the file for any framework, version detection  in `server/index.js` is going to break.
Instead of `packageLockJSON.dependencies[packageName]` the new format looks like `packageLockJSON.packages.[''].dependencies.[packageName]`. See e.g. [https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json](https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json).
Also, some frameworks (e.g. Ember), put their core dependency, from which version should be derived, into `devDependencies` instead of `dependencies`.
This PR tries to remedy these situations, but I understand you might prefer a different solution :D, as this one is fairly ugly/might use JS features outside your preferred `node` support matrix. …

[WIP] Fix framework detection for a new package-lock.json format

---

frameworks/non-keyed/halogen/.gitignore
frameworks/non-keyed/halogen/index.html
frameworks/non-keyed/halogen/package-lock.json
frameworks/non-keyed/halogen/package.json
frameworks/non-keyed/halogen/packages.dhall
frameworks/non-keyed/halogen/spago.dhall
frameworks/non-keyed/halogen/src/Main.js
frameworks/non-keyed/halogen/src/Main.purs

This PR:
- Updates Halogen to v7.0.0
- Updates PureScript to v0.15.8
- Updates Spago to v0.20.9
- Replaces `build-prod` script to make use of [purs-backend-es](https://github.com/aristanetworks/purescript-backend-optimizer) (optimizer).

update Halogen to v7.0.0

---

broken-frameworks/keyed/dojo/package-lock.json
broken-frameworks/keyed/dojo/package.json

Fixes the dojo build for node 18. On an m1 the install requires to be run with `--ignore-scripts` flag
Fixes #1212

Fix build for dojo

---

webdriver-ts/src/playwrightAccess.ts
webdriver-ts/src/puppeteerAccess.ts

* Update file path for Chrome on Windows to use 64-bit version.
On my Windows 11 Version 22H2 machine I needed to update the paths for Chrome to use the 64-bit version, which I believe should be the new standard.

Update file path for Chrome on Windows

---

webdriver-ts-results/package.json

* Add glob support for rimraf for Windows hosts.
Tested on:
- Ubuntu 20.04.5 LTS
- Windows 11 Version 22H2
```rimraf``` version 4.2+ puts glob support for systems that don't natively support globs behind the ```--glob``` option.
With this change users on Windows can build the results table. 
Don't believe there are adverse impacts to non-Windows users, but I haven't tested on a macOS machine.

Add glob support for rimraf for Windows

---

frameworks/keyed/svelte/package-lock.json
frameworks/keyed/svelte/package.json
frameworks/non-keyed/svelte/package-lock.json
frameworks/non-keyed/svelte/package.json

* Update Svelte keyed and non-keyed to version 3.58.0.
Tested on:
```
Node v18.15.0
npm 9.5.0
```
Keyed:
```
npm run isKeyed keyed/svelte
> webdriver-ts@1.0.0 isKeyed
> cross-env LANG="en_US.UTF-8" node dist/isKeyed.js keyed/svelte
args.framework undefined true
Frameworks that will be checked svelte-v3.58.0-keyed
*** headless undefined
svelte-v3.58.0-keyed is keyed for 'run benchmark' and keyed for 'remove row benchmark' and keyed for 'swap rows benchmark' . It'll appear as keyed in the results
```
Non-keyed:
```
npm run isKeyed non-keyed/svelte 
> webdriver-ts@1.0.0 isKeyed
> cross-env LANG="en_US.UTF-8" node dist/isKeyed.js non-keyed/svelte
args.framework undefined true
Frameworks that will be checked svelte-v3.58.0-non-keyed
*** headless undefined
svelte-v3.58.0-non-keyed is non-keyed …
```

Update Svelte to version 3.58.0

---

frameworks/non-keyed/slingjs/index.html
frameworks/non-keyed/slingjs/package-lock.json
frameworks/non-keyed/slingjs/package.json
frameworks/non-keyed/slingjs/src/controller.js

* Update Sling.js to version 18.1.0.
Tested on:
```
Node v18.15.0
npm 9.5.0
```
```
npm run isKeyed non-keyed/slingjs
> webdriver-ts@1.0.0 isKeyed
> cross-env LANG="en_US.UTF-8" node dist/isKeyed.js non-keyed/slingjs
args.framework undefined true
Frameworks that will be checked slingjs-v18.1.0-non-keyed
*** headless undefined
slingjs-v18.1.0-non-keyed is non-keyed for 'run benchmark' and non-keyed for 'remove row benchmark' and non-keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results
```

Update Sling.js to version 18.1.0

---

frameworks/keyed/plaited/index.html
frameworks/keyed/plaited/package-lock.json
frameworks/keyed/plaited/package.json
frameworks/keyed/plaited/src/main.tsx
frameworks/keyed/plaited/tsconfig.json

Adds plaited library to benchmarks

plaited 3.0.0

---

frameworks/keyed/lwc/package-lock.json
frameworks/keyed/lwc/package.json
frameworks/keyed/lwc/rollup.config.js
frameworks/keyed/lwc/src/bench/app/app.html
frameworks/keyed/lwc/src/bench/app/app.js

Updates `lwc` from `2.7.3` to `3.0.1`. Also tweaks the benchmark a bit to avoid some unnecessary dynamic attributes in the table rows.

chore: update lwc to v3

---

cleanup.js

- Add JSDoc types.
- Replace rimraf with fs.rmSync: reduce memory consumption by 33% (600kb vs ~900kb) and reduce cleanup execution time by 25% (80ms vs 110ms).
- Changed node_modules folder deletion to rmIfExists()
- Move path.join() outside the rmIfExists() function.
- Put cleanup start in a separate function.

refactor: cleanup.js

---

rebuild-all.js

- Add JSDoc comments and types.
- Split the code into functions.
- Use more meaningful names for variables and functions.
- Simplify getting args.
- Replace var and let with const where possible.
- Replace string concatenation with string templates.

refactor: rebuild-add.js

---

rebuild-single.js

- Add a dockerCmd assignment using a ternary operator.
- Simplify the assignment of args.
- Replace var and let with const where possible.
- Format with prettier.

refactor: rebuild-single.js

---

configureStyles.js

- Add default values for `bootstrap` and `minimal`.
- Replace `var` and `let` with `const`.
- Replace synchronous calls to the file system with asynchronous ones.
- Split the code.
- Remove the commented code because its functionality was duplicated from the `copy.js` files.

refactor: configureStyles.js

---

checkObsolete.js

- Add cache for duplicated frameworks - packet inspection accelerated from 350s to 260s (by about 35%).
- Add JSDoc comments and types.
- Split code into functions.
- Change the type of passing framework data from `package.json` from array to object.
- Remove if...else hell.
- Format with prettier.

Refactor checkObsolote.js

---

webdriver-ts/.eslintrc.json
webdriver-ts/package.json
webdriver-ts/src/benchmarkRunner.ts

Fixed 2 bugs:
1. Eslint in VSCode could not find `typescript.json` in `.eslintrc.json` `parserOptions.parser`, so could not lint typescirpt files.
2. When calling `npm run lint` script, eslint tried to check all files in the root directory (i.e. `webdriver-ts`), but could not check `jest.config.js` because the configuration file jest was not specified in the `include` property in `tsconfig.json`. Now running 'npm run lint' will only check files in the src directory.

fix(webdriver-ts): eslint configuration

---

frameworks/keyed/incremental-dom/index.html
frameworks/keyed/incremental-dom/package-lock.json
frameworks/keyed/incremental-dom/package.json
frameworks/keyed/incremental-dom/src/components/button.ts
frameworks/keyed/incremental-dom/src/components/div.ts
frameworks/keyed/incremental-dom/src/components/header.ts
frameworks/keyed/incremental-dom/src/components/span.ts
frameworks/keyed/incremental-dom/src/components/table.ts
frameworks/keyed/incremental-dom/src/data-collection.ts
frameworks/keyed/incremental-dom/src/main.ts

This PR adds Google's Incremental DOM to the JS-Framework-Benchmark repo.
Incremental DOM is a library for building up DOM trees and updating them in-place when data changes. It differs from the established virtual DOM approach in that no intermediate tree is created (the existing tree is mutated in-place). This approach significantly reduces memory allocation and GC thrashing for incremental updates to the DOM tree therefore increasing performance significantly in some cases.
Incremental DOM is primarily intended as a compilation target for templating languages. It could be used to implement a higher level API for human consumption. The API was carefully designed to minimize heap allocations and where unavoidable ensure that as many objects as possible can be de-allocated by incremental …

Introduce Google's IncrementalDOM library to JS Benchmarks.

---

webdriver-ts/src/.prettierrc
webdriver-ts/src/benchmarkRunner.ts
webdriver-ts/src/benchmarksCommon.ts
webdriver-ts/src/benchmarksLighthouse.ts
webdriver-ts/src/benchmarksPlaywright.ts
webdriver-ts/src/benchmarksPuppeteer.ts
webdriver-ts/src/benchmarksWebdriverAfterframe.ts
webdriver-ts/src/common.ts
webdriver-ts/src/createIndex.ts
webdriver-ts/src/createResultJS.ts
webdriver-ts/src/forkedBenchmarkRunnerPlaywright.ts
webdriver-ts/src/forkedBenchmarkRunnerPuppeteer.ts
webdriver-ts/src/forkedBenchmarkRunnerWebdriverAfterframe.ts
webdriver-ts/src/forkedBenchmarkRunnerWebdriverCDP.ts
webdriver-ts/src/interval.test.ts
webdriver-ts/src/isCSPCompliant.ts
webdriver-ts/src/isKeyed.ts
webdriver-ts/src/parseTrace.ts
webdriver-ts/src/puppeteerAccess.ts
webdriver-ts/src/timeline.ts
webdriver-ts/src/webdriverAccess.ts
webdriver-ts/src/webdriverCDPAccess.ts
webdriver-ts/src/writeResults.ts

- Remove most unused imports, variables and functions.
- Remove .prettierrc.

Remove unused vars in webdriver-ts and remove .prettierrc

---

frameworks/keyed/vanjs/bundle.sh
frameworks/keyed/vanjs/index.html
frameworks/keyed/vanjs/minify.sh
frameworks/keyed/vanjs/package-lock.json
frameworks/keyed/vanjs/package.json
frameworks/keyed/vanjs/src/Main.js

This PR adds the benchmark test for VanJS.
VanJS (https://vanjs.org/) is by far the world smallest reactive UI framework. Here are its key features:
- **Ultra-lightweight:** 0.9kB in gzipped minified bundle. 50~100 times smaller than most popular UI frameworks.
- **Zero-dependency:** No dependencies on any other library, no JSX, no transpiling. A true grab-n-go library that enables people to build UI right away.
- **Unopinionated:** Supports multiple programming paradigms: You can use it in a way similar to React, or occasionally manipulate DOM tree directly for performance or for convenience.
I ran the benchmark many times locally:
The geometric mean consistently lies around 1.12 ~ 1.15 (close to vanillajs and much lower than react). Some adjustments on implementations (optimization …

Add benchmark for VanJS

---

frameworks/keyed/lit-html/package-lock.json
frameworks/keyed/lit-html/package.json
frameworks/keyed/lit-html/rollup.config.js
frameworks/keyed/lit/package-lock.json
frameworks/keyed/lit/package.json
frameworks/non-keyed/lit-html/package-lock.json
frameworks/non-keyed/lit-html/package.json
frameworks/non-keyed/lit-html/rollup.config.js
frameworks/non-keyed/lit/package-lock.json
frameworks/non-keyed/lit/package.json

Closes #1430
I saw lit performance improve v2 -> v3, which is cool!
I saw lit-html get slower v1 -> v3, and I don't know why - @justinfagnani if you know of any changes that should be made when moving from v1 to v3, I'd love to know.
Keyed results:

update lit, lit-html

---

frameworks/keyed/cample/package-lock.json
frameworks/keyed/cample/package.json

I think this update should fix the select row to more adequate speed values, because 32.7 seconds when the maximum speed is somewhere around 10 seconds is...

Update cample to v3.2.0-beta.1

---

frameworks/keyed/wasm-bindgen/package.json

the cargo.toml says 0.2.84, but the package.json only said 0.2.47

fix wasm-bindgen version

---

frameworks/keyed/s2/package-lock.json
frameworks/keyed/s2/package.json
frameworks/keyed/s2/src/bench.js

Since I got pinged [here](https://github.com/krausest/js-framework-benchmark/issues/1421), I might as well update it.

Update s2 to use published version from npm

---

frameworks/keyed/rendrjs/src/App.js

Swap leads to a runtime error. This version was derived from a react implementation, which has the same bug (#1469).

Rendrjs: Fix swap bug fix

---

frameworks/keyed/uhtml/index.html
frameworks/keyed/uhtml/package-lock.json
frameworks/keyed/uhtml/package.json
frameworks/keyed/uhtml/rollup.config.js
frameworks/keyed/uhtml/src/index.js
frameworks/keyed/uhtml/src/jumbotron.js
frameworks/keyed/uhtml/src/table-delegate.js
frameworks/keyed/uhtml/src/table-tr.js
frameworks/keyed/uhtml/src/table.js
frameworks/non-keyed/uhtml/index.html
frameworks/non-keyed/uhtml/package-lock.json
frameworks/non-keyed/uhtml/package.json
frameworks/non-keyed/uhtml/rollup.config.js
frameworks/non-keyed/uhtml/src/jumbotron.js
frameworks/non-keyed/uhtml/src/table-delegate.js

[uhtml v4 is out](https://github.com/WebReflection/uhtml/pull/86) so I'd like to have it tested and validated with all its improvements in here too, thank you!
* update *uhtml* to its latest
* update all dependencies to avoid deprecation warnings while bundling
* changed minimal amount of code to validate results against previous version, without changing any other logic behind the test

Update uhtml to v4

---

frameworks/keyed/plaited/package-lock.json
frameworks/keyed/plaited/package.json
frameworks/keyed/plaited/src/main.tsx

This PR is for 5.3.0 of Plaited
This version
- drops **useStore** (doesn't make sense with library architecture and coding style)
- splits **$.render** into **$.render** and **$.insert** The later which use the same interface pattern as ` insertAdjacentElement` but takes a spread like `append | prepend | before | after`
- introduces a new **$.clone** method that can be used to clone an element with a **data-target** attribute and apply a callback to the clone before usage. Useful for handling large list and reducing parse time. 
- makes use of a streamlined **createTemplate** aka **h** function to improve templating script times. 
Glad this benchmark repo exist @krausest! It's been super useful in improving my library.

feat(plaited): uses new features and improved  function for templating

---

frameworks/keyed/karyon/package.json
frameworks/keyed/karyon/src/app.js

This updates the `karyon` module version, also implementation due to removal of the so-called "selector" API, a peculiar feature not really compliant with the module concept. Frankly speaking, it was just a crutch for [#800](https://github.com/krausest/js-framework-benchmark/issues/800) issue. However, a naive approach will hurt performance, thus a similar "selector" was added into the implementation itself, hopefully it won't be a subject for new note, sort of "explicit select delegation".

`karyon` update

---

frameworks/keyed/cample/package-lock.json
frameworks/keyed/cample/package.json

Optimized the assembly of templates for rows, made select row a little faster. I think this will work for 1.10, but not 1.08-1.09. I don’t know anymore, it’s unlikely that before the new year it will be possible to implement the code that I had in mind, but I think the result will be cool. Due to the specific syntax, “select row” is of course too slow, result certainly stands out from all the green ones, but I think there are still optimization ideas, so that’s fine.

Update cample to v.3.2.0-beta.7

---

frameworks/keyed/cample/package-lock.json
frameworks/keyed/cample/package.json

Overall, I think I've fixed a lot of bugs now that were slowing down results. Perhaps now it will be possible to fix “select row” and make the results for this test satisfactory. I believe that the syntax of the framework will allow the results to reach even the level of 1.04-1.06, but it feels like the code is at level 1.08-1.10 now. Next, it will be necessary to redo the assembly of templates, I think this is already work for about a couple of weeks or months, so I hope the next pull request for the test will be in 2024 (I think I didn’t break anything. I tested , but who knows what could break there).
Thank you very much for devoting your time to review and test the implementation of this framework. Happy New Year 2024!

Update cample to v3.2.0-beta.8

---

frameworks/non-keyed/reken/index.html
frameworks/non-keyed/reken/js/Main.js
frameworks/non-keyed/reken/js/reken.js
frameworks/non-keyed/reken/package-lock.json
frameworks/non-keyed/reken/package.json

Add Reken version v0.9.6 to non-keyed js-framework-benchmark.
I ran the verification:
Also ran the benchmark and a comparison against non-keyed vanillajs:

Add Reken framework version 0.9.6

---

frameworks/keyed/gxt/package-lock.json
frameworks/keyed/gxt/package.json
frameworks/keyed/gxt/src/main.ts
frameworks/keyed/gxt/vite.config.mts

Fixed `clear row regression` (44ms -> 25ms)

update glimmer-next [fix remove rows regression]

---

frameworks/keyed/uhtml/package-lock.json
frameworks/keyed/uhtml/package.json
frameworks/non-keyed/uhtml/package-lock.json
frameworks/non-keyed/uhtml/package.json

This MR would like to benchmark latest uhtml v4 with the following changes:
* even lower memory consumption
* linear render (interpolations are never looped more than once)
* overall simplified logic but also made it more robust for fragment edge cases
* hints around both fragments (not used in this demo), via `` and ``, and array of items (used in this demo), via `` pinned comments
Thanks for considering updating this library to its greatest version *yet* 😉

Update uhtml to v4.4

---

frameworks/keyed/stencil/package-lock.json
frameworks/keyed/stencil/package.json

This patch updates StencilJS to `v4.11`

Update Stencil to v4.11

---

frameworks/non-keyed/slingjs/index.html
frameworks/non-keyed/slingjs/package-lock.json
frameworks/non-keyed/slingjs/package.json
frameworks/non-keyed/slingjs/src/controller.js

* Update Sling.js to version 21.0.1.
* Benchmark ran correctly locally.
After ```npm ci``` and ```npm run build-prod```:
```
==== Results of PlausibilityCheck:
successful run
```

Update Sling.js to version 21.0.1

---

frameworks/keyed/cample/package-lock.json
frameworks/keyed/cample/package.json

Hello! I hope the framework will have time to get into the results for version 122. In general, this pr I am 99.99999% sure that it will be 1.09 or lower!

Update cample to v.3.2.0-alpha.12

---

frameworks/keyed/ember/app/components/my-table.gjs

It's idiomatic to use `{{on}}` for event listening, and `{{on}}` is the only way to have _conditionally applied_ / dynamic event listeners, but for performance sensitive situations, we can _do less_ by using the platform, and we don't need any cleanup behavior, so native `onclick` should be sufficient, and I think I'm going to push for this being default in the ember learning materials
The improvement to speed _is noticeable_
There was a concern mentioned by a community member about `onclick` only being able to be set once, but [here is how this works in a real app](https://limber.glimdown.com/edit?c=MQAg9gdgxgNgllA1iALgUwM4oFDYLQgDaAUgMogBiATgIYC2aA7mFcgEJrQAWdNrIcOgAcqYAG5oGEFBgC6ACi4oUQjAC4A9BoDmcFFwCuAIwB0UMHQ2JaBjJhQaAVhjwAzWg2as8RzlB58iBpCBjAwGgCMAGwADAAcAJQg%2BEQAInAYULYYcJCoYCD%2BN …

[Ember]: Use native onclick

---

frameworks/keyed/svelte-classic/package-lock.json
frameworks/keyed/svelte-classic/package.json
frameworks/keyed/svelte-classic/src/Main.svelte
frameworks/keyed/svelte/package-lock.json
frameworks/keyed/svelte/package.json
frameworks/non-keyed/svelte-classic/package-lock.json
frameworks/non-keyed/svelte-classic/package.json
frameworks/non-keyed/svelte-classic/src/Main.svelte

Since below mentioned issue is resolved, "svelte 5 classic" can now (next.61) run the and significantly speed up the code from "svelte 4" without any modification.
- https://github.com/sveltejs/svelte/issues/9521
This is really impressive @trueadm ! Svelte 5 is gonna be a great success with this level of backwards compat

Bump to Svelte next.61

---

frameworks/keyed/cample/package-lock.json
frameworks/keyed/cample/package.json

I think that it will no longer be 1.09, but will be somewhere around 1.06 - 1.07! Even if it’s 1.08, I think that it will be quite possible to finish up to 1.03 - 1.06 in the near future. I found a lot of stupid errors in the code, I think there will be more. I think I’ll finish it up to 1.03 - 1.06, although I see that I seem to have accelerated "select row" to almost maximum on the local machine, and the values are higher than others. In principle, I have almost completed the maximum of the framework. Maybe I’ll do a couple of PRs and we can say that the implementation will be ready. It will only be updated as new functionality is introduced, such as working with asynchronous data, etc.
P.S. Well, this time I’m not even 99.99999% sure, but 109% sure)

Update cample to 3.2.0-alpha.15

---

frameworks/keyed/bobril/index.html
frameworks/keyed/bobril/package-lock.json
frameworks/keyed/bobril/package.json
frameworks/keyed/bobril/src/app.ts

Update Bobril 20.6.4 without dynamically creating css

---

frameworks/keyed/cample/package-lock.json
frameworks/keyed/cample/package.json
frameworks/keyed/cample/src/main.js

That's it, I understood how the code would work faster and better. I'll combine the code from version 29 and version 39 and it will work fine. In version 29, "select row" was super slower, the rest was normal. Now, "select row" is fixed, so I think it's better this way. I hope the framework has time to get into the results of version 124

Update cample to 3.2.0-alpha.44

---

frameworks/keyed/vanillajs-lite/index.html
frameworks/keyed/vanillajs-lite/package-lock.json
frameworks/keyed/vanillajs-lite/package.json
frameworks/keyed/vanillajs-lite/src/Main.js

This is intended as a fix for issue #1661 (you may need to test it first in your environment before making a decision).
Due to convoluted [vanillajs](https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/vanillajs/src/Main.js) implementation which makes the optimization difficult, I did a complete rewrite with minimal abstractions and cleaner execution flow, for a better visibility of current and future optimization paths.
It shows promising results in my environment (Ubuntu 23.10, Google Chrome for Testing
Version 124.0.6367.91 (Official Build) (64-bit)):
[results.json](https://github.com/krausest/js-framework-benchmark/files/15237974/results.json)

Add `vanillajs-lite` implementation (#1661 fix)

---

frameworks/keyed/vanillajs-lite/src/Main.js

This fixes isKeyed test for `vanillajs-lite` (by mimicking `ivi` behavior):
> vanillajs-lite-keyed is keyed for 'run benchmark' and keyed for 'remove row benchmark' and keyed for 'swap rows benchmark' . It'll appear as keyed in the results

fix `vanillajs-lite` for isKeyed test

---

webdriver-ts-results/src/Common.ts

Render empty results at the end of the table for easier local benchmarking. Fixes #1577

Render empty results at the end of the table

---

webdriver-ts/src/forkedBenchmarkRunnerPlaywright.ts
webdriver-ts/src/forkedBenchmarkRunnerPuppeteer.ts

Use last-resort gc, fixes #1667
Relevant discussion here as to why this change is being made https://github.com/krausest/js-framework-benchmark/issues/1661#issuecomment-2099578793. TLDR: regular GC passes no longer seem enough to collect all orphaned dom nodes from warm-up runs.

Use last-resort gc, fixes #1667

---

frameworks/keyed/vanillajs-lite/src/Main.js

This update fixes memory issue for "creating/clearing 1k rows" test which seems to be caused by hybrid rows clearing feature (tbody.remove()/tbody.textContent = '') issued in the most recent update. Also, some refactoring to reduce the file size.
The changes seems to not have much impact on CPU tests results:

`vanillajs-lite` update

---

frameworks/keyed/re-frame/.gitignore
frameworks/keyed/re-frame/index.html
frameworks/keyed/re-frame/package-lock.json
frameworks/keyed/re-frame/package.json
frameworks/keyed/re-frame/project.clj
frameworks/keyed/re-frame/src/demo/main.cljs

This is a first stab at a [re-frame](https://github.com/day8/re-frame) benchmark, a ClojureScript library on top of reagent/react.
It is heavily based on https://github.com/krausest/js-framework-benchmark/pull/343 `keyed/reagent` for the build process and DOM structure, thank you @Deraen!

Add keyed/re-frame bench

---

frameworks/keyed/solid-store/rollup.config.js
frameworks/keyed/solid-store/src/main.jsx
frameworks/keyed/solid/rollup.config.js
frameworks/keyed/solid/src/main.jsx

1. Clean up `keyed/solid` & `keyed/solid-store` implementations by running Prettier & adopting patterns from other framework setups for clearer code & better uniformity
1. Update `keyed/solid` & `keyed/solid-store` rollup configs with a minimal terser setup to more reasonably represent what the average user will experience when using a boilerplate or popular framework like `SolidStart`.
> Is this over-optimization? _No._ I believe this is firmly in the spirit of representing what an average user will realistically experience with Solid. Plus, this is considerably less bundler customization than what is used in many of the other framework benchmarks, like [million](https://github.com/krausest/js-framework-benchmark/blob/9fcbe016d312baaf4c2a14dff3d5f2fc2ffbe290/frameworks/keyed/million/rollu …

refactor solid & solid-store implementations

---

webdriver-ts/src/puppeteerAccess.ts

fixes the [#20957eb](https://github.com/krausest/js-framework-benchmark/commit/20957eb82a78ce840997d3f9594cd516aeea0306)

fix `--disable-features` switch

---

frameworks/keyed/cample/package-lock.json
frameworks/keyed/cample/package.json
frameworks/keyed/cample/src/main.js

I solved the problem with the click without resorting to the methods described [here](https://github.com/krausest/js-framework-benchmark/issues/772). The main idea is a stack of real UI, where I store state that is not in contact with the main data. That is, this can be compared to how if we entered some data into the "input", and so this data is, as it were, reflected in this idea.
I don't know, maybe this is a trivial idea, but it sounds interesting to create a separate stack for each DOM element.

Update cample to v3.2.1-beta.0

---

frameworks/keyed/svelte-classic/package-lock.json
frameworks/keyed/svelte-classic/package.json
frameworks/keyed/svelte/package-lock.json
frameworks/keyed/svelte/package.json
frameworks/non-keyed/svelte-classic/package-lock.json
frameworks/non-keyed/svelte-classic/package.json

There were some bugs in Svelte 165 that affected performance, they should be fixed in this update.

Update svelte to 5.0.0-next.174

---

frameworks/keyed/react-compiler-hooks/index.html
frameworks/keyed/react-compiler-hooks/package-lock.json
frameworks/keyed/react-compiler-hooks/package.json
frameworks/keyed/react-compiler-hooks/src/main.jsx
frameworks/keyed/react-compiler-hooks/src/utils.js
frameworks/keyed/react-compiler-hooks/webpack.config.js

Adds a React benchmark that uses [React Compiler](https://react.dev/learn/react-compiler) babel plugin.
**Notes:**
- This benchmark aims to be as simple as possible and demonstrate performance without (almost) any manual memoization. 
- It's not using the `useReducer` [trick](https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/react-hooks/src/main.jsx) of passing single `dispatch` to all children. While it's a valid pattern I don't think it reflects the majority of the "regular" react code as it forces children to know action types and how to call dispatch which couples them to this interface. This benchmark is keeping it simple with just `useState` and regular functions created during render, which, in my opinion, reflects the vast majority of code written in …

Add react-compiler-hooks (React 19 RC)

---

frameworks/keyed/gxt/package-lock.json
frameworks/keyed/gxt/package.json
frameworks/keyed/gxt/src/Row.gts
frameworks/keyed/gxt/vite.config.mts

Bumping `gxt` from `v37` to `v57`, memory usage & cleanup logic should be improved.
Also, see some regression in create-many case.
Prev: https://github.com/krausest/js-framework-benchmark/pull/1593

chore: update gtx to 0.0.57

---

frameworks/keyed/sonnet/package-lock.json
frameworks/keyed/sonnet/package.json
frameworks/non-keyed/sonnet/package-lock.json
frameworks/non-keyed/sonnet/package.json

Bump sonnet to `0.0.33`

---

frameworks/keyed/ivi/package-lock.json
frameworks/keyed/ivi/package.json
frameworks/keyed/ivi/src/main.ts
frameworks/keyed/ivi/tsconfig.json

this switches ivi to use its [@ivi/htm](https://github.com/localvoid/ivi/blob/master/packages/@ivi/htm/README.md) template syntax, which i think makes this awesome framework feel a lot less esoteric. the compiled bundle is identical.
i've kept the `.textContent` prop optimizations in place, but will do a follow-up PR to see how much omitting these affects performance. (@localvoid says memory usage would go up slightly)

update ivi and switch template to @ivi/htm

---

frameworks/keyed/angular-cf-new-nozone/.browserslistrc
frameworks/keyed/angular-cf-new-nozone/.gitignore
frameworks/keyed/angular-cf-new-nozone/.npmrc
frameworks/keyed/angular-cf-new-nozone/README.md
frameworks/keyed/angular-cf-new-nozone/angular.json
frameworks/keyed/angular-cf-new-nozone/package-lock.json
frameworks/keyed/angular-cf-new-nozone/package.json
frameworks/keyed/angular-cf-new-nozone/src/app/app.component.html
frameworks/keyed/angular-cf-new-nozone/src/app/app.component.ts
frameworks/keyed/angular-cf-new-nozone/src/index.html
frameworks/keyed/angular-cf-new-nozone/src/main.ts
frameworks/keyed/angular-cf-new-nozone/tsconfig.app.json
frameworks/keyed/angular-cf-new-nozone/tsconfig.json

Angular 18 was merged except for the new zoneless implementation which is kept in this PR

[WIP] move the no-zone implementation with provideExperimentalZonelessChangeDetection to new PR

---

frameworks/keyed/targetj/index.html
frameworks/keyed/targetj/package-lock.json
frameworks/keyed/targetj/package.json
frameworks/keyed/targetj/src/data.js
frameworks/keyed/targetj/src/main.js
frameworks/keyed/targetj/webpack.config.js

This requests adds the TargetJ framework to the js-framework-benchmark repository.
**Key changes:**
index.html: contains the main HTML structure
src/main.js: implements benchmark functionality using TargetJ.
src/data.js: creates the data sample
package.json and package-lock.json: define the dependencies

Add TargetJ to js-framework-benchmark

---

frameworks/non-keyed/aurelia2/babel.config.json
frameworks/non-keyed/aurelia2/index.html
frameworks/non-keyed/aurelia2/package-lock.json
frameworks/non-keyed/aurelia2/package.json
frameworks/non-keyed/aurelia2/src/main.js
frameworks/non-keyed/aurelia2/src/my-app.html
frameworks/non-keyed/aurelia2/src/my-app.js
frameworks/non-keyed/aurelia2/src/store.js
frameworks/non-keyed/aurelia2/vite.config.js

Adds Aurelia 2 into the non-keyed frameworks list.

Add Aurelia 2 to non-keyed frameworks.

---

frameworks/keyed/angular-cf-signals-nozone/src/app/app.component.ts

ngFor import is useless becouse template use @for

chore: remove useless import of ngFor

---

frameworks/keyed/plaited/package-lock.json
frameworks/keyed/plaited/package.json
frameworks/keyed/plaited/src/main.tsx

Upgrades plaited library to version 7.0.0

chore: upgrade plaited to 7.0.0

---

frameworks/keyed/plaited/package-lock.json
frameworks/keyed/plaited/package.json
frameworks/keyed/plaited/src/main.tsx
frameworks/keyed/plaited/tsconfig.json

[Fix] upgrade to 7.2.0 to fix performance regressions
Renames defineTemplate to defineElement to prevent confusion around usage of new useTemplate utility. This utility is a renamed/refactored clone helper focused on just HTMLTemplateElements. The version 5.3.0 clone helper was originally inspired by SolidJS's For component and I totally forgot why when I removed it. 
This PR should restore performance, or get me close to 5.3.0, while keeping with additional features in v7. I expect this to be the last PR for quite awhile.  Making SSR first framework perform client side this well has been a challenge.

Plaited 7.2.0

---

frameworks/keyed/crank/src/main.jsx

The usage of `crank-key` is probably causing regressions because of console deprecation warnings. 0.7 will be released soon and I’d love to have an accurate comparison.
Thanks for this project!

Fix Crank to use non-deprecated key prop

---

frameworks/keyed/ripple/index.html
frameworks/keyed/ripple/package-lock.json
frameworks/keyed/ripple/package.json
frameworks/keyed/ripple/rollup.config.js
frameworks/keyed/ripple/src/Main.ripple
frameworks/keyed/ripple/src/main.js

Adds [Ripple](ripplejs.com). Unfortunately, I'm on my old MacBook M1 Pro and running the benchmarks locally takes forever and is wildly inconsistent each time – so I have no idea how bad Ripple is.

Add Ripple
